(() => {
  'use strict';
  let API=null;
  const $=id=>document.getElementById(id);
  const state={month:new Date(),filter:'all',agendaFilter:'all',ctx:null};
  state.month=new Date(state.month.getFullYear(),state.month.getMonth(),1);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const dateIso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const fmtLong=v=>{const d=API.dateObj(v);return d?d.toLocaleDateString('ar-SA',{weekday:'long',day:'numeric',month:'long',year:'numeric'}):'—'};
  function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').hidden=true,2600)}
  function gateError(title,msg){$('gateSpinner').hidden=true;$('gateIcon').hidden=false;$('gateTitle').textContent=title;$('gateMessage').textContent=msg;$('gateActions').hidden=false}
  function categoryLabel(c){return{program:'برنامج',occasion:'مناسبة',custom:'تذكير',meeting:'اجتماع',deadline:'موعد نهائي',followup:'متابعة',plan:'خطة'}[c]||c}
  function visibleReminder(r){if(state.filter==='all')return true;if(state.filter==='critical')return r.priority==='critical';if(state.filter==='program')return String(r.kind).includes('program');if(state.filter==='progress')return ['low_progress','unfinished_plan','inactive_plan'].includes(r.kind);return true}
  function renderSummary(){const rem=state.ctx.reminders||[],plans=state.ctx.plans||[];$('totalAlerts').textContent=String(rem.length);$('criticalAlerts').textContent=String(rem.filter(x=>x.priority==='critical').length);$('upcomingPrograms').textContent=String(rem.filter(x=>x.kind==='program_upcoming').length);const active=plans.filter(p=>p.status!=='completed');const avg=active.length?Math.round(active.reduce((s,p)=>s+Number(p.completion_rate||0),0)/active.length):0;$('avgProgress').textContent=`${avg}%`;const low=rem.find(x=>x.kind==='low_progress'||x.kind==='unfinished_plan');$('warningBanner').hidden=!low;if(low)$('warningBanner').innerHTML=`<b>${esc(low.title)}</b> — ${esc(low.message)}`}
  function eventClass(e){if(e.status==='not_done')return'not_done';return e.category||'custom'}
  function renderCalendar(){const year=state.month.getFullYear(),month=state.month.getMonth();$('monthTitle').textContent=state.month.toLocaleDateString('ar-SA',{month:'long',year:'numeric'});const first=new Date(year,month,1),start=new Date(year,month,1-first.getDay());const today=API.isoToday();let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=dateIso(d),inside=d.getMonth()===month,events=(state.ctx.events||[]).filter(e=>e.date===iso||(e.endDate&&e.date<=iso&&e.endDate>=iso));const chips=events.slice(0,3).map(e=>`<span class="event-chip ${esc(eventClass(e))}" title="${esc(e.title)}">${esc(e.title)}</span>`).join('');html+=`<div class="day-cell ${inside?'':'outside'} ${iso===today?'today':''}" data-day="${iso}"><div class="day-head"><span class="day-num">${d.getDate()}</span>${events.length?`<small>${events.length}</small>`:''}</div>${chips}${events.length>3?`<span class="more-events">+ ${events.length-3} أخرى</span>`:''}</div>`}$('calendarGrid').innerHTML=html;$('calendarGrid').querySelectorAll('[data-day]').forEach(c=>c.onclick=()=>openDay(c.dataset.day))}
  function openDay(iso){const events=(state.ctx.events||[]).filter(e=>e.date===iso||(e.endDate&&e.date<=iso&&e.endDate>=iso));$('dayModalTitle').textContent=fmtLong(iso);$('dayModalList').innerHTML=events.length?events.map(e=>`<article class="day-event"><h3>${esc(e.title)}</h3><p>${esc(categoryLabel(e.category))}${e.endDate&&e.endDate!==e.date?` · حتى ${esc(API.fmtDate(e.endDate))}`:''}</p>${e.source==='custom'?`<button class="btn secondary" data-delete-custom="${esc(e.id)}">حذف التذكير</button>`:''}</article>`).join(''):'<div class="empty">لا توجد مواعيد في هذا اليوم.</div>';$('dayModal').hidden=false;$('dayModalList').querySelectorAll('[data-delete-custom]').forEach(b=>b.onclick=async()=>{if(!confirm('حذف هذا التذكير؟'))return;await API.deleteCustomEvent(b.dataset.deleteCustom);state.ctx=API.state;renderAll();$('dayModal').hidden=true;toast('تم حذف التذكير')})}
  function renderReminders(){const list=(state.ctx.reminders||[]).filter(visibleReminder);$('reminderList').innerHTML=list.length?list.slice(0,30).map(r=>`<article class="reminder ${esc(r.priority)} ${r.unread?'unread':''}"><div class="reminder-bar"></div><div><h3>${esc(r.title)}</h3><p>${esc(r.message)}</p><small>${esc(API.fmtDate(r.date))}</small><div class="reminder-actions"><button data-read="${esc(r.key)}">تم الاطلاع</button><button data-snooze="${esc(r.key)}">غدًا</button>${r.planId?`<a href="../plans/index.html?from=portal">فتح الخطة</a>`:''}</div></div></article>`).join(''):'<div class="empty">لا توجد تنبيهات ضمن هذا التصنيف.</div>';$('reminderList').querySelectorAll('[data-read]').forEach(b=>b.onclick=async()=>{await API.markRead(b.dataset.read);state.ctx=API.state;renderAll()});$('reminderList').querySelectorAll('[data-snooze]').forEach(b=>b.onclick=async()=>{await API.snooze(b.dataset.snooze,24);state.ctx=API.state;renderAll();toast('تم تأجيل التنبيه إلى الغد')})}
  function renderAgenda(){const today=API.isoToday(),end=new Date();end.setDate(end.getDate()+30);const endIso=dateIso(end);let events=(state.ctx.events||[]).filter(e=>(e.date>=today&&e.date<=endIso)||e.status==='not_done');if(state.agendaFilter!=='all')events=events.filter(e=>e.category===state.agendaFilter);events=events.sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(0,36);$('agendaList').innerHTML=events.length?events.map(e=>`<article class="agenda-item"><span>${esc(categoryLabel(e.category))}</span><h3>${esc(e.title)}</h3><p>${esc(API.fmtDate(e.date))}${e.endDate&&e.endDate!==e.date?` — ${esc(API.fmtDate(e.endDate))}`:''}</p><div class="agenda-actions"><small>${e.status==='done'?'تم التنفيذ':e.status==='not_done'?'لم ينفذ':e.status==='pending'?'بانتظار التنفيذ':''}</small>${e.source==='custom'?`<button data-delete-custom="${esc(e.id)}">حذف</button>`:''}</div></article>`).join(''):'<div class="empty">لا توجد عناصر قادمة في الفترة المحددة.</div>';$('agendaList').querySelectorAll('[data-delete-custom]').forEach(b=>b.onclick=async()=>{if(!confirm('حذف التذكير؟'))return;await API.deleteCustomEvent(b.dataset.deleteCustom);state.ctx=API.state;renderAll();toast('تم الحذف')})}
  function expectedProgress(plan){const s=API.dateObj(plan.start_date),e=API.dateObj(plan.end_date),n=API.dateObj(API.isoToday());if(!s||!e||!n)return null;if(n<=s)return 0;if(n>=e)return 100;return Math.round(((n-s)/(e-s))*100)}
  function renderPlans(){const plans=state.ctx.plans||[];$('planProgressList').innerHTML=plans.length?plans.slice(0,1).map(p=>{const actual=Math.round(Number(p.completion_rate||0)),expected=expectedProgress(p),lag=expected==null?0:expected-actual;return`<article class="plan-progress"><div class="plan-progress-head"><div><h3>${esc(p.title||'خطة الموجه الطلابي')}</h3><small>${esc(p.term_name||'')} · ${esc(p.academic_year||'')}</small></div><strong>${actual}%</strong></div><div class="track"><i style="width:${actual}%"></i></div><p>نفذ ${Number(p.completed_items||0)} من ${Number(p.total_items||0)} عنصر. ${expected!=null?`المتوقع زمنيًا نحو ${expected}%${lag>=20?` — متأخر ${lag} نقطة`:''}.`:''}</p></article>`}).join(''):'<div class="empty">لا توجد خطط محفوظة. أنشئ خطة أولًا من منصة خطة الموجه الطلابي.</div>'}
  function renderAll(){renderSummary();renderCalendar();renderReminders();renderAgenda();renderPlans()}
  async function refresh(){$('refreshButton').disabled=true;try{await API.loadContext(true);state.ctx=API.state;renderAll();toast('تم تحديث التقويم والتنبيهات')}catch(e){toast('تعذر التحديث')}finally{$('refreshButton').disabled=false}}
  function bind(){
    $('prevMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};$('nextMonth').onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};$('todayButton').onclick=()=>{const n=new Date();state.month=new Date(n.getFullYear(),n.getMonth(),1);renderCalendar()};$('refreshButton').onclick=refresh;$('retryButton').onclick=()=>location.reload();$('closeDayModal').onclick=()=>$('dayModal').hidden=true;$('dayModal').onclick=e=>{if(e.target===$('dayModal'))$('dayModal').hidden=true};
    document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderReminders()});$('agendaFilter').onchange=()=>{state.agendaFilter=$('agendaFilter').value;renderAgenda()};
    $('addCustomEvent').onclick=async()=>{const title=$('customTitle').value.trim(),date=$('customDate').value;if(!title||!date){$('customStatus').hidden=false;$('customStatus').className='status error';$('customStatus').textContent='اكتب عنوان التذكير والتاريخ.';return}$('addCustomEvent').disabled=true;try{await API.createCustomEvent({title,event_date:date,category:$('customCategory').value,priority:$('customPriority').value,details:$('customDetails').value});state.ctx=API.state;$('customTitle').value='';$('customDetails').value='';$('customStatus').hidden=false;$('customStatus').className='status';$('customStatus').textContent='تمت إضافة التذكير إلى التقويم.';renderAll()}catch(e){$('customStatus').hidden=false;$('customStatus').className='status error';$('customStatus').textContent='تعذر إضافة التذكير.'}finally{$('addCustomEvent').disabled=false}};
    $('browserNotifyButton').onclick=async()=>{const result=await API.requestBrowserPermission();if(result==='granted'){toast('تم تفعيل إشعارات المتصفح على هذا الجهاز');$('browserNotifyButton').textContent='🔔 الإشعارات مفعّلة'}else if(result==='denied')toast('تم رفض إذن الإشعارات من المتصفح');else toast('المتصفح لا يدعم الإشعارات')};
  }
  async function init(){
    API=window.GuidanceReminderAPI;
    if(!API||typeof API.loadContext!=='function'){
      return gateError('ملفات التقويم غير مكتملة','تعذر تحميل محرك التقويم الذكي (smart-reminders.js). ارفع جميع ملفات V19.0.3 إلى جذر المستودع ثم أعد تحميل الصفحة.');
    }
    bind();
    try{
      await Promise.race([API.loadContext(true),new Promise((_,reject)=>setTimeout(()=>reject(new Error('calendar_boot_timeout')),18000))]);
      state.ctx=API.state;
      if(!state.ctx.user)return gateError('يلزم تسجيل الدخول','ارجع إلى البوابة وسجّل الدخول ثم افتح التقويم من داخلها.');
      if(!state.ctx.access)return gateError('ميزة الباقة الشاملة فقط','التقويم الذكي والتنبيهات متاحان حصريًا للباقة الشاملة الشهرية أو السنوية، وكذلك كود هدية الباقة الشاملة.');
      $('gate').hidden=true;$('app').hidden=false;$('customDate').value=API.isoToday();
      if('Notification'in window&&Notification.permission==='granted')$('browserNotifyButton').textContent='🔔 الإشعارات مفعّلة';
      renderAll();
    }catch(e){
      console.error('Calendar init failed',e);
      gateError('تعذر فتح التقويم',e?.message==='calendar_boot_timeout'?'استغرق الاتصال وقتًا أطول من اللازم. تحقق من الإنترنت ثم أعد المحاولة.':'تعذر تحميل بيانات الخطة والتنبيهات. ارجع إلى البوابة ثم أعد المحاولة.');
    }
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
