
(function(){'use strict';
var SUPABASE_URL='https://fpicgtldwfevdvpbxkjf.supabase.co';var SUPABASE_KEY='sb_publishable_3C7eKHRkzE2T-OLOpfue4g_i3u4R7Ay';var PROJECT_REF='fpicgtldwfevdvpbxkjf';var SCHOOL_EDITION=true;
var $=function(id){return document.getElementById(id)};var PROGRAMS=window.REPORT_PROGRAMS||[];var state={session:null,user:null,account:{},entitlements:[],annualAccess:false,program:null,activities:[],evaluation:{},evidence:[],logo:null,currentDraftId:null};

var NAV_ROUTES={results_analysis:{label:'تحليل النتائج',href:'../analysis/index.html'},guidance_records:{label:'السجلات الرقمية',href:'../records/index.html'},presentations:{label:'العروض التقديمية',href:'../presentations/index.html'},counselor_plan:{label:'خطة الموجه',href:'../plans/index.html'},achievement_reports:{label:'تقارير الإنجاز',href:'../reports/index.html'},messages_library:{label:'مراسلات ولي الأمر',href:'../messages/index.html'}};
var NAV_ICONS={results_analysis:'<svg viewBox="0 0 24 24"><path d="M4 19V9M10 19V5M16 19v-7M22 19H2"/></svg>',guidance_records:'<svg viewBox="0 0 24 24"><path d="M6 3h9l3 3v15H6z"/><path d="M15 3v4h4M9 11h6M9 15h6"/></svg>',presentations:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="12" rx="2"/><path d="M8 21l4-5 4 5M8 9h3M8 12h7"/></svg>',counselor_plan:'<svg viewBox="0 0 24 24"><path d="M6 3h12v18H6z"/><path d="M9 7h6M9 11h6M9 15h3"/><path d="m15 16 1.4 1.4L19 14.8"/></svg>',achievement_reports:'<svg viewBox="0 0 24 24"><path d="M5 3h14v18H5z"/><path d="M8 8h8M8 12h8M8 16h5"/><path d="m15 17 1.5 1.5L20 15"/></svg>',messages_library:'<svg viewBox="0 0 24 24"><path d="M4 5h16v12H7l-3 3z"/><path d="M8 9h8M8 13h5"/></svg>'};
function navActiveEntitlements(){return (state.entitlements||[]).filter(function(e){return e&&e.is_active!==false&&e.expires_at&&new Date(e.expires_at).getTime()>Date.now()})}
function navHasAccess(code){if(SCHOOL_EDITION)return true;if(state.account&&state.account.is_system_admin)return true;if(code==='messages_library')return !!state.annualAccess;return navActiveEntitlements().some(function(e){return e.product_code==='all_access'||e.product_code===code})}
function renderUnifiedNav(){var bar=$('unifiedPlatformBar'),box=$('platformSwitcher'),badge=$('platformPlanBadge');if(!bar||!box||!badge)return;box.innerHTML=Object.keys(NAV_ROUTES).filter(function(code){return code!=='messages_library'}).map(function(code){var item=NAV_ROUTES[code],icon=NAV_ICONS[code]||'',current=code==='achievement_reports';if(!navHasAccess(code)&&!current)return '<span class="platform-tab locked"><span class="platform-tab-icon">'+icon+'</span><span class="platform-tab-copy"><strong>'+item.label+'</strong><small>غير مفعّلة</small></span></span>';return '<a class="platform-tab'+(current?' current':'')+'" href="'+item.href+'?from=portal"><span class="platform-tab-icon">'+icon+'</span><span class="platform-tab-copy"><strong>'+item.label+'</strong><small>'+(current?'المنصة الحالية':'انتقال إلى المنصة')+'</small></span></a>'}).join('');var active=navActiveEntitlements(),label=state.account&&state.account.is_system_admin?'مدير النظام':(active.some(function(e){return e.product_code==='all_access'})?'الباقة الشاملة':'اشتراك مفعل');badge.innerHTML='<span class="platform-plan-status"></span><span class="platform-plan-copy"><span>الباقة الحالية</span><strong>'+escapeHTML(label)+'</strong><small>التنقل بين الخدمات المفعلة</small></span>';bar.hidden=false}

var evaluationCriteria=['تحقق أهداف البرنامج','مساهمة البرنامج في القضية الاستراتيجية','فعالية البرنامج','تعاون الفريق','ملاءمة الميزانية','تنفيذ البرنامج وفق المراحل المعدة','ملاءمة مكان التنفيذ','تفاعل المستفيدين'];
function timeout(p,ms){return Promise.race([p,new Promise(function(_,rej){setTimeout(function(){rej(new Error('network_timeout'))},ms)})])}
function findSession(){var keys=[];for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf('sb-')===0&&k.slice(-11)==='-auth-token')keys.push(k)}var preferred='sb-'+PROJECT_REF+'-auth-token';keys.sort(function(a){return a===preferred?-1:1});for(var j=0;j<keys.length;j++){try{var raw=JSON.parse(localStorage.getItem(keys[j]));var s=raw&&((raw.currentSession)||(raw.session)||raw);if(s&&s.access_token&&s.refresh_token)return s}catch(e){}}return null}
function api(path,opt){opt=opt||{};var headers={apikey:SUPABASE_KEY,Authorization:'Bearer '+(opt.token||SUPABASE_KEY),Accept:'application/json','Content-Type':'application/json'};if(opt.prefer)headers.Prefer=opt.prefer;return timeout(fetch(SUPABASE_URL+path,{method:opt.method||'GET',headers:headers,body:opt.body?JSON.stringify(opt.body):undefined}),12000).then(function(r){return r.text().then(function(t){var data=t?JSON.parse(t):null;if(!r.ok){var e=new Error((data&&data.message)||'request_failed');e.status=r.status;throw e}return data})})}
function verifySession(session){return api('/auth/v1/user',{token:session.access_token}).then(function(user){return {session:session,user:user}}).catch(function(err){if(err.status!==401)throw err;return api('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:session.refresh_token}}).then(function(fresh){try{localStorage.setItem('sb-'+PROJECT_REF+'-auth-token',JSON.stringify(fresh))}catch(e){}return api('/auth/v1/user',{token:fresh.access_token}).then(function(user){return {session:fresh,user:user}})})})}
function gateError(title,msg){$('gateSpinner').hidden=true;$('gateIcon').hidden=false;$('gateTitle').textContent=title;$('gateMessage').textContent=msg;$('gateActions').hidden=false}
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;clearTimeout(toast.t);toast.t=setTimeout(function(){$('toast').hidden=true},2800)}
function escapeHTML(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function lines(v){return String(v||'').split(/\n+/).map(function(x){return x.trim()}).filter(Boolean)}
function adaptText(v){var girls=$('audienceSelect').value==='girls';return String(v||'').replace(/الطلاب/g,girls?'الطالبات':'الطلاب').replace(/الطالب(?!ات)/g,girls?'الطالبة':'الطالب').replace(/أبنائهم/g,girls?'بناتهن':'أبنائهم').replace(/أبنائكم/g,girls?'بناتكم':'أبنائكم').replace(/زملائهم/g,girls?'زميلاتهن':'زملائهم').replace(/زملائه/g,girls?'زميلاتها':'زملائه').replace(/المتفوقين/g,girls?'المتفوقات':'المتفوقين').replace(/المتميزين/g,girls?'المتميزات':'المتميزين')}
function stageLabel(){return {lower_primary:'الابتدائية الدنيا',upper_primary:'الابتدائية العليا',middle:'المتوسطة',secondary:'الثانوية'}[$('stageSelect').value]}
function listText(arr){return (arr||[]).join('\n')}
function populatePrograms(filter){filter=(filter||'').trim();var current=$('programSelect').value;$('programSelect').innerHTML=PROGRAMS.filter(function(p){return !filter||p.title.indexOf(filter)>=0||p.category.indexOf(filter)>=0}).map(function(p){return '<option value="'+p.id+'">'+escapeHTML(p.title)+' — '+escapeHTML(p.category)+'</option>'}).join('');if(current&&$('programSelect').querySelector('option[value="'+current+'"]'))$('programSelect').value=current}
function reportDirectory(){return (window.MishkatSchoolDirectory||window.MishkatBubbleDirectory)?.getSnapshot?.()||{employees:[]}}
function employeeRows(){return reportDirectory().employees||[]}
function employeeById(id){return employeeRows().find(e=>String(e.id)===String(id))||null}
function resolveEmployeeHint(hint){
  var text=String(hint||'').trim(),ctx=window.MishkatSchoolContext?.getContext?.()||{};
  if(/الموجه|الموجهة/.test(text))return employeeById(ctx.id)||employeeRows().find(e=>e.name===ctx.counselorName)||null;
  if(/مدير المدرسة|مديرة المدرسة/.test(text))return employeeById(ctx.managerId)||employeeRows().find(e=>e.name===ctx.managerName)||null;
  return employeeRows().find(e=>e.name===text)||null;
}
function employeeOptions(selectedId,hint){
  var selected=String(selectedId||resolveEmployeeHint(hint)?.id||'');
  return '<option value="">اختر الموظف</option>'+employeeRows().map(e=>'<option value="'+escapeHTML(e.id)+'"'+(String(e.id)===selected?' selected':'')+'>'+escapeHTML(e.name)+'</option>').join('');
}
async function loadReportDirectory(){
  var dir=window.MishkatSchoolDirectory||window.MishkatBubbleDirectory;
  try{if(dir?.load)await dir.load()}catch(e){console.warn('Report employee directory unavailable',e)}
  var ctx=window.MishkatSchoolContext?.getContext?.()||{},selected=resolveEmployeeHint(ctx.counselorName||'الموجه الطلابي');
  $('executorInput').innerHTML=employeeOptions(selected?.id||ctx.id,ctx.counselorName||'الموجه الطلابي');
}
function loadProgram(id,keepMeta){var p=PROGRAMS.find(function(x){return x.id===id})||PROGRAMS[0];if(!p)return;state.program=p;$('titleInput').value=adaptText(p.title);$('generalObjectiveInput').value=adaptText(p.generalObjective);$('objectivesInput').value=adaptText(listText(p.objectives));$('indicatorsInput').value=adaptText(listText(p.indicators));$('mechanismInput').value=adaptText(listText(p.mechanism));$('difficultiesInput').value=adaptText(p.difficulties);$('actionsInput').value=adaptText(p.actions);$('positivesInput').value=adaptText(listText(p.positives));$('negativesInput').value=adaptText(p.negatives);$('lessonsInput').value=adaptText(p.lessons);state.activities=(p.activities||[]).map(function(a){var owner=resolveEmployeeHint(a[2]),sup=resolveEmployeeHint(a[3]);return {name:adaptText(a[0]),details:adaptText(a[1]),owner:owner?.name||'',ownerId:owner?.id||'',supervisor:sup?.name||'',supervisorId:sup?.id||''}});renderActivities();if(!keepMeta){var st=(p.stages||[])[0];if(st&&st!=='all')$('stageSelect').value=st}$('sourceBadge').textContent='نموذج جاهز: '+p.category;renderPreview()}
function activityRow(a,i){return '<tr><td>'+(i+1)+'</td><td><input data-a="name" data-i="'+i+'" value="'+escapeHTML(a.name)+'"></td><td><textarea data-a="details" data-i="'+i+'">'+escapeHTML(a.details)+'</textarea></td><td><select data-a="ownerId" data-person="employee" data-i="'+i+'">'+employeeOptions(a.ownerId,a.owner)+'</select></td><td><select data-a="supervisorId" data-person="employee" data-i="'+i+'">'+employeeOptions(a.supervisorId,a.supervisor)+'</select></td><td><button class="row-delete" data-delete-activity="'+i+'">حذف</button></td></tr>'}
function renderActivities(){$('activitiesBody').innerHTML=state.activities.map(activityRow).join('');$('activitiesBody').querySelectorAll('[data-a]').forEach(function(el){el.onchange=el.oninput=function(){var a=state.activities[+this.dataset.i];if(this.dataset.person==='employee'){var emp=employeeById(this.value);a[this.dataset.a]=this.value;if(this.dataset.a==='ownerId')a.owner=emp?.name||'';if(this.dataset.a==='supervisorId')a.supervisor=emp?.name||'';}else a[this.dataset.a]=this.value}});$('activitiesBody').querySelectorAll('[data-delete-activity]').forEach(function(b){b.onclick=function(){state.activities.splice(+this.dataset.deleteActivity,1);renderActivities()}})}
function renderEvaluation(){evaluationCriteria.forEach(function(c){if(!state.evaluation[c])state.evaluation[c]='high'});$('evaluationGrid').innerHTML=evaluationCriteria.map(function(c){return '<div class="evaluation-item"><span>'+c+'</span><div class="rating">'+[['high','عالية'],['medium','متوسطة'],['low','ضعيفة']].map(function(x){return '<button data-criterion="'+escapeHTML(c)+'" data-rating="'+x[0]+'" class="'+(state.evaluation[c]===x[0]?'active':'')+'">'+x[1]+'</button>'}).join('')+'</div></div>'}).join('');$('evaluationGrid').querySelectorAll('[data-rating]').forEach(function(b){b.onclick=function(){state.evaluation[this.dataset.criterion]=this.dataset.rating;renderEvaluation()}})}
function compressImage(file){return new Promise(function(resolve,reject){var reader=new FileReader();reader.onerror=reject;reader.onload=function(){var img=new Image();img.onerror=reject;img.onload=function(){var max=1500,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.round(img.width*scale),h=Math.round(img.height*scale),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',.78))};img.src=reader.result};reader.readAsDataURL(file)})}
function addEvidence(files){var list=[].slice.call(files).slice(0,16-state.evidence.length);Promise.all(list.map(function(f){return compressImage(f).then(function(src){return {id:Date.now()+Math.random(),src:src,caption:f.name.replace(/\.[^.]+$/,'')}})})).then(function(items){state.evidence=state.evidence.concat(items);renderEvidence();renderPreview()}).catch(function(){toast('تعذر قراءة بعض الصور')})}
function renderEvidence(){$('evidenceCount').textContent=state.evidence.length+' / 16';$('evidenceGrid').innerHTML=state.evidence.map(function(e,i){return '<article class="evidence-card"><img src="'+e.src+'"><div class="caption"><input data-caption="'+i+'" value="'+escapeHTML(e.caption)+'" placeholder="وصف الشاهد"><div class="evidence-actions"><button data-move-up="'+i+'">↑</button><button data-move-down="'+i+'">↓</button><button data-remove-evidence="'+i+'">حذف</button></div></div></article>'}).join('');$('evidenceGrid').querySelectorAll('[data-caption]').forEach(function(x){x.oninput=function(){state.evidence[+this.dataset.caption].caption=this.value}});$('evidenceGrid').querySelectorAll('[data-remove-evidence]').forEach(function(x){x.onclick=function(){state.evidence.splice(+this.dataset.removeEvidence,1);renderEvidence()}});$('evidenceGrid').querySelectorAll('[data-move-up]').forEach(function(x){x.onclick=function(){var i=+this.dataset.moveUp;if(i>0){var t=state.evidence[i-1];state.evidence[i-1]=state.evidence[i];state.evidence[i]=t;renderEvidence()}}});$('evidenceGrid').querySelectorAll('[data-move-down]').forEach(function(x){x.onclick=function(){var i=+this.dataset.moveDown;if(i<state.evidence.length-1){var t=state.evidence[i+1];state.evidence[i+1]=state.evidence[i];state.evidence[i]=t;renderEvidence()}}})}
function formData(){var ctx=window.MishkatSchoolContext&&window.MishkatSchoolContext.getContext?window.MishkatSchoolContext.getContext():{};return {version:'16.1.0',draftId:state.currentDraftId,programId:state.program&&state.program.id,audience:$('audienceSelect').value,stage:$('stageSelect').value,term:ctx.term||$('termSelect').value,year:ctx.academicYear||$('yearInput').value,date:$('dateInput').value,school:ctx.schoolName||$('schoolInput').value,counselor:ctx.counselorName||$('counselorInput').value,executor:employeeById($('executorInput').value)?.name||'',executorId:$('executorInput').value,supervisor:ctx.managerName||$('supervisorInput').value,beneficiaries:$('beneficiariesInput').value,location:$('locationInput').value,title:$('titleInput').value,generalObjective:$('generalObjectiveInput').value,objectives:$('objectivesInput').value,indicators:$('indicatorsInput').value,mechanism:$('mechanismInput').value,fundingType:$('fundingTypeInput').value,budgetItem:$('budgetItemInput').value,amount:$('amountInput').value,team:$('teamInput').value,difficulties:$('difficultiesInput').value,actions:$('actionsInput').value,positives:$('positivesInput').value,negatives:$('negativesInput').value,lessons:$('lessonsInput').value,activities:state.activities,evaluation:state.evaluation,evidence:state.evidence,logo:state.logo,updatedAt:new Date().toISOString()}}
function applyData(d){if(!d)return;state.currentDraftId=d.draftId||null;state.program=PROGRAMS.find(function(p){return p.id===d.programId})||PROGRAMS[0];if(state.program)$('programSelect').value=state.program.id;['stage','term','year','date','school','counselor','executor','supervisor','beneficiaries','location','title','generalObjective','objectives','indicators','mechanism','fundingType','budgetItem','amount','team','difficulties','actions','positives','negatives','lessons'].forEach(function(k){var id={audience:'audienceSelect',stage:'stageSelect',term:'termSelect',year:'yearInput',date:'dateInput',school:'schoolInput',counselor:'counselorInput',executor:'executorInput',supervisor:'supervisorInput',beneficiaries:'beneficiariesInput',location:'locationInput',title:'titleInput',generalObjective:'generalObjectiveInput',objectives:'objectivesInput',indicators:'indicatorsInput',mechanism:'mechanismInput',fundingType:'fundingTypeInput',budgetItem:'budgetItemInput',amount:'amountInput',team:'teamInput',difficulties:'difficultiesInput',actions:'actionsInput',positives:'positivesInput',negatives:'negativesInput',lessons:'lessonsInput'}[k];if(id&&d[k]!=null){if(id==='executorInput'){var emp=employeeRows().find(e=>e.name===d[k]||String(e.id)===String(d.executorId||''));if(emp)$(id).value=emp.id;}else $(id).value=d[k]}});state.activities=d.activities||[];state.evaluation=d.evaluation||{};state.evidence=d.evidence||[];state.logo=d.logo||null;renderActivities();renderEvaluation();renderEvidence();renderPreview()}
function section(title,body){return '<section class="report-section"><h3>'+title+'</h3>'+body+'</section>'}
function ul(v){return '<ul>'+lines(adaptText(v)).map(function(x){return '<li>'+escapeHTML(x)+'</li>'}).join('')+'</ul>'}
function reportHTML(){var d=formData(),aud=d.audience==='girls'?'طالبات':'طلاب',logo=d.logo?'<img src="'+d.logo+'">':'<div></div>',date=d.date?new Date(d.date+'T00:00:00').toLocaleDateString('ar-SA'):'—';var pages=[];pages.push('<section class="report-page cover"><div class="cover-box"><div class="report-brand">'+logo+'<div><h3>'+escapeHTML(d.school||'اسم المدرسة')+'</h3><small>تقارير الإنجاز للموجه الطلابي</small></div></div><h1>تقرير إنجاز برنامج</h1><h2>'+escapeHTML(adaptText(d.title))+'</h2><p>'+escapeHTML(d.term)+' · '+escapeHTML(d.year)+'</p><div class="cover-meta"><div><b>مسؤول التنفيذ</b><br>'+escapeHTML(adaptText(d.executor))+'</div><div><b>المشرف العام</b><br>'+escapeHTML(d.supervisor)+'</div><div><b>الفئة المستهدفة</b><br>'+aud+' · '+stageLabel()+'</div><div><b>تاريخ التنفيذ</b><br>'+date+'</div><div><b>المكان</b><br>'+escapeHTML(d.location||'—')+'</div><div><b>عدد المستفيدين</b><br>'+escapeHTML(d.beneficiaries||'—')+'</div></div></div><div class="page-footer"><span>'+escapeHTML(d.school||'المدرسة')+'</span><span>1</span></div></section>');
var p2='<div class="report-brand">'+logo+'<h3>'+escapeHTML(adaptText(d.title))+'</h3></div>'+section('الهدف العام','<p>'+escapeHTML(adaptText(d.generalObjective))+'</p>')+section('أهداف البرنامج',ul(d.objectives))+section('مؤشرات تحقيق الأهداف',ul(d.indicators))+section('آلية التنفيذ',ul(d.mechanism))+section('تكلفة البرنامج','<p><b>مصدر التمويل:</b> '+escapeHTML(d.fundingType)+' &nbsp; <b>البند:</b> '+escapeHTML(d.budgetItem||'—')+' &nbsp; <b>المبلغ:</b> '+escapeHTML(d.amount||'—')+'</p>');pages.push('<section class="report-page">'+p2+'<div class="page-footer"><span>'+escapeHTML(d.school||'المدرسة')+'</span><span>2</span></div></section>');
var act='<table class="report-table"><thead><tr><th>م</th><th>الفعالية</th><th>التفاصيل</th><th>مسؤول التنفيذ</th><th>المشرف</th></tr></thead><tbody>'+d.activities.map(function(a,i){return '<tr><td>'+(i+1)+'</td><td>'+escapeHTML(adaptText(a.name))+'</td><td>'+escapeHTML(adaptText(a.details))+'</td><td>'+escapeHTML(adaptText(a.owner))+'</td><td>'+escapeHTML(a.supervisor)+'</td></tr>'}).join('')+'</tbody></table>';var evalTable='<table class="report-table"><thead><tr><th>عنصر التقويم</th><th>عالية</th><th>متوسطة</th><th>ضعيفة</th></tr></thead><tbody>'+evaluationCriteria.map(function(c){var r=d.evaluation[c]||'high';return '<tr><td>'+c+'</td><td>'+(r==='high'?'✓':'')+'</td><td>'+(r==='medium'?'✓':'')+'</td><td>'+(r==='low'?'✓':'')+'</td></tr>'}).join('')+'</tbody></table>';pages.push('<section class="report-page"><div class="report-brand">'+logo+'<h3>خطة البرنامج وتقويمه</h3></div>'+section('مراحل البرنامج والفعاليات',act)+section('فريق العمل','<p>'+escapeHTML(adaptText(d.team))+'</p>')+section('تقييم البرنامج',evalTable)+'<div class="page-footer"><span>'+escapeHTML(d.school||'المدرسة')+'</span><span>3</span></div></section>');
var p4='<div class="report-brand">'+logo+'<h3>نتائج التنفيذ والتوصيات</h3></div>'+section('أهم الصعوبات والمعوقات','<p>'+escapeHTML(adaptText(d.difficulties))+'</p>')+section('الإجراءات المتخذة للتغلب عليها','<p>'+escapeHTML(adaptText(d.actions))+'</p>')+section('أهم الإيجابيات',ul(d.positives))+section('الملاحظات والسلبيات','<p>'+escapeHTML(adaptText(d.negatives))+'</p>')+section('الدروس المستخلصة والتوصيات','<p>'+escapeHTML(adaptText(d.lessons))+'</p>');pages.push('<section class="report-page">'+p4+'<div class="page-footer"><span>'+escapeHTML(d.school||'المدرسة')+'</span><span>4</span></div></section>');
for(var i=0;i<d.evidence.length;i+=4){var imgs=d.evidence.slice(i,i+4).map(function(e){return '<figure class="report-evidence"><img src="'+e.src+'"><p>'+escapeHTML(e.caption||'شاهد من تنفيذ البرنامج')+'</p></figure>'}).join('');pages.push('<section class="report-page"><div class="report-brand">'+logo+'<h3>شواهد التنفيذ</h3></div><div class="evidence-page-grid">'+imgs+'</div><div class="page-footer"><span>'+escapeHTML(d.school||'المدرسة')+'</span><span>'+(5+Math.floor(i/4))+'</span></div></section>')}
return '<div class="report-document">'+pages.join('')+'</div>'}
function renderPreview(){$('previewHost').innerHTML=reportHTML()}
function dbOpen(){return new Promise(function(resolve,reject){var r=indexedDB.open('guidance_reports_v16',1);r.onupgradeneeded=function(){var db=r.result;if(!db.objectStoreNames.contains('drafts'))db.createObjectStore('drafts',{keyPath:'id'})};r.onsuccess=function(){resolve(r.result)};r.onerror=function(){reject(r.error)}})}
function saveDraft(){var d=formData();d.id=state.currentDraftId||('draft_'+Date.now());d.draftId=d.id;state.currentDraftId=d.id;return dbOpen().then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put(d);tx.oncomplete=resolve;tx.onerror=function(){reject(tx.error)}})}).then(function(){toast('تم حفظ المسودة')})}
function listDrafts(){return dbOpen().then(function(db){return new Promise(function(resolve,reject){var r=db.transaction('drafts').objectStore('drafts').getAll();r.onsuccess=function(){resolve(r.result||[])};r.onerror=function(){reject(r.error)}})})}
function deleteDraft(id){return dbOpen().then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').delete(id);tx.oncomplete=resolve;tx.onerror=function(){reject(tx.error)}})})}
function showDrafts(){listDrafts().then(function(ds){ds.sort(function(a,b){return String(b.updatedAt).localeCompare(String(a.updatedAt))});$('draftsList').innerHTML=ds.length?ds.map(function(d){return '<article class="draft-item"><div><h3>'+escapeHTML(d.title||'مسودة بلا عنوان')+'</h3><p>'+new Date(d.updatedAt).toLocaleString('ar-SA')+'</p></div><div class="draft-actions"><button class="btn secondary small" data-load="'+d.id+'">فتح</button><button class="btn secondary small" data-del="'+d.id+'">حذف</button></div></article>'}).join(''):'<p>لا توجد مسودات محفوظة.</p>';$('draftsModal').hidden=false;$('draftsList').querySelectorAll('[data-load]').forEach(function(b){b.onclick=function(){var id=this.dataset.load;var d=ds.find(function(x){return x.id===id});applyData(d);$('draftsModal').hidden=true}});$('draftsList').querySelectorAll('[data-del]').forEach(function(b){b.onclick=function(){deleteDraft(this.dataset.del).then(showDrafts)}})})}
function exportJSON(){var blob=new Blob([JSON.stringify(formData(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='تقرير_'+($('titleInput').value||'برنامج')+'.json';a.click();URL.revokeObjectURL(a.href)}
function exportWord(){var css='<style>body{font-family:Arial;direction:rtl}.report-page{page-break-after:always;padding:20px}.report-brand{border-bottom:4px solid #69b54a}.report-section{border:1px solid #ccc;margin:10px;padding:10px}.report-section h3{background:#e9f5ee;padding:6px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #999;padding:6px}.evidence-page-grid{display:grid;grid-template-columns:1fr 1fr}.report-evidence img{max-width:100%}</style>';var html='<html><head><meta charset="utf-8">'+css+'</head><body>'+reportHTML()+'</body></html>';var blob=new Blob(['\ufeff',html],{type:'application/msword'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='تقرير_'+($('titleInput').value||'برنامج')+'.doc';a.click();URL.revokeObjectURL(a.href)}
function wire(){populatePrograms('');$('programSearch').oninput=function(){populatePrograms(this.value)};$('programSelect').onchange=function(){loadProgram(this.value)};$('addActivityButton').onclick=function(){var ctx=window.MishkatSchoolContext?.getContext?.()||{},own=resolveEmployeeHint(ctx.counselorName||'الموجه الطلابي'),sup=resolveEmployeeHint(ctx.managerName||'مدير المدرسة');state.activities.push({name:'فعالية جديدة',details:'اكتب تفاصيل الفعالية',owner:own?.name||'',ownerId:own?.id||'',supervisor:sup?.name||'',supervisorId:sup?.id||''});renderActivities()};document.querySelectorAll('.tab').forEach(function(b){b.onclick=function(){document.querySelectorAll('.tab').forEach(function(x){x.classList.remove('active')});document.querySelectorAll('.tab-panel').forEach(function(x){x.classList.remove('active')});this.classList.add('active');$('tab-'+this.dataset.tab).classList.add('active');if(this.dataset.tab==='preview')renderPreview()}});$('evidenceInput').onchange=function(){addEvidence(this.files);this.value=''};var dz=$('dropZone');['dragenter','dragover'].forEach(function(e){dz.addEventListener(e,function(x){x.preventDefault();dz.classList.add('drag')})});['dragleave','drop'].forEach(function(e){dz.addEventListener(e,function(x){x.preventDefault();dz.classList.remove('drag')})});dz.addEventListener('drop',function(e){addEvidence(e.dataTransfer.files)});$('logoInput').onchange=function(){var f=this.files[0];if(!f)return;compressImage(f).then(function(src){state.logo=src;renderPreview()})};$('refreshPreviewButton').onclick=renderPreview;$('printButton').onclick=function(){$('printRoot').innerHTML=reportHTML();setTimeout(function(){window.print()},100)};$('wordButton').onclick=exportWord;$('saveDraftButton').onclick=saveDraft;$('openDraftsButton').onclick=showDrafts;$('closeDraftsButton').onclick=function(){$('draftsModal').hidden=true};$('exportJsonButton').onclick=exportJSON;$('importJsonInput').onchange=function(){var f=this.files[0];if(!f)return;f.text().then(function(t){applyData(JSON.parse(t));toast('تم استيراد التقرير')}).catch(function(){toast('ملف غير صالح')});this.value=''};$('newReportButton').onclick=function(){state.currentDraftId=null;state.evidence=[];state.logo=null;loadProgram($('programSelect').value);renderEvidence();toast('تم فتح تقرير جديد')};['stageSelect','termSelect','yearInput','dateInput','schoolInput','counselorInput','executorInput','supervisorInput','beneficiariesInput','locationInput','titleInput','generalObjectiveInput','objectivesInput','indicatorsInput','mechanismInput','fundingTypeInput','budgetItemInput','amountInput','teamInput','difficultiesInput','actionsInput','positivesInput','negativesInput','lessonsInput'].forEach(function(id){$(id).addEventListener('input',function(){if(id==='stageSelect'&&state.program)loadProgram(state.program.id,true)})})}
async function boot(){
  if(SCHOOL_EDITION){await loadReportDirectory();var ctx=window.MishkatSchoolContext&&window.MishkatSchoolContext.getContext?window.MishkatSchoolContext.getContext():{};state.session=null;state.user={id:ctx.id||'mishkat-school-user',email:''};state.account={full_name:ctx.counselorName||'الموجه الطلابي',school_name:ctx.schoolName||'مدارس المشكاة الأهلية',is_system_admin:false,presentation_audience_type:ctx.schoolType==='girls'?'girls':'boys'};state.entitlements=[];state.annualAccess=true;state.logo=null;$('schoolInput').value=ctx.schoolName||state.account.school_name;$('counselorInput').value=ctx.counselorName||state.account.full_name;$('supervisorInput').value=ctx.managerName||$('supervisorInput').value;if(ctx.academicYear)$('yearInput').value=ctx.academicYear;if(ctx.term)$('termSelect').value=ctx.term;var aud=ctx.schoolType==='girls'?'girls':'boys';$('audienceSelect').value=aud;$('accountBadge').textContent=aud==='girls'?'تقارير الطالبات':'تقارير الطلاب';$('reportAudienceLabel').textContent=aud==='girls'?'بنات':'بنين';$('dateInput').value=new Date().toISOString().slice(0,10);renderUnifiedNav();wire();renderEvaluation();loadProgram(PROGRAMS[0].id);$('gate').hidden=true;$('app').hidden=false;return;}
  var found=findSession();if(!found){gateError('يلزم تسجيل الدخول','ارجع إلى البوابة وسجّل الدخول ثم افتح تقارير الإنجاز من داخلها.');return}verifySession(found).then(function(r){state.session=r.session;state.user=r.user;return Promise.all([api('/rest/v1/premium_accounts?select=full_name,school_name,school_logo_data,is_system_admin,presentation_audience_type&user_id=eq.'+encodeURIComponent(r.user.id)+'&limit=1',{token:r.session.access_token}).catch(function(){return []}),api('/rest/v1/premium_entitlements?select=product_code,billing_period,expires_at,is_active&user_id=eq.'+encodeURIComponent(r.user.id),{token:r.session.access_token}).catch(function(){return []}),api('/rest/v1/rpc/premium_has_annual_access',{method:'POST',token:r.session.access_token,body:{p_user_id:r.user.id}}).catch(function(){return false})])}).then(function(res){state.account=Array.isArray(res[0])?(res[0][0]||{}):(res[0]||{});state.entitlements=res[1]||[];state.annualAccess=res[2]===true;var active=state.entitlements.some(function(e){return e.is_active!==false&&new Date(e.expires_at)>new Date()&&(e.product_code==='achievement_reports'||e.product_code==='all_access')}),admin=!!state.account.is_system_admin;if(!active&&!admin){gateError('تقارير الإنجاز غير مفعلة','اشترك في منصة تقارير الإنجاز بـ10 ريالات شهريًا أو 50 ريالًا سنويًا، أو فعّل الباقة الشاملة.');return}state.logo=state.account.school_logo_data||null;var ctx=window.MishkatSchoolContext&&window.MishkatSchoolContext.getContext?window.MishkatSchoolContext.getContext():{};$('schoolInput').value=ctx.schoolName||state.account.school_name||'';$('counselorInput').value=ctx.counselorName||state.account.full_name||'';$('supervisorInput').value=ctx.managerName||$('supervisorInput').value;if(ctx.academicYear)$('yearInput').value=ctx.academicYear;if(ctx.term)$('termSelect').value=ctx.term;var aud=state.account.presentation_audience_type||localStorage.getItem('guidance_audience_type')||'boys';$('audienceSelect').value=aud;$('accountBadge').textContent=aud==='girls'?'تقارير الطالبات':'تقارير الطلاب';$('reportAudienceLabel').textContent=aud==='girls'?'بنات':'بنين';$('dateInput').value=new Date().toISOString().slice(0,10);renderUnifiedNav();wire();renderEvaluation();loadProgram(PROGRAMS[0].id);$('gate').hidden=true;$('app').hidden=false}).catch(function(e){console.error(e);gateError('تعذر فتح المنصة',e.message==='network_timeout'?'استغرقت خدمة التحقق وقتًا أطول من المعتاد. اضغط إعادة المحاولة.':'انتهت الجلسة أو تعذر الاتصال. ارجع إلى البوابة وسجّل الدخول مرة أخرى.')})}
$('retryButton').onclick=function(){location.reload()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
