(function(){'use strict';
const SUPABASE_URL='https://fpicgtldwfevdvpbxkjf.supabase.co';
const SUPABASE_KEY='sb_publishable_3C7eKHRkzE2T-OLOpfue4g_i3u4R7Ay';
const PROJECT_REF='fpicgtldwfevdvpbxkjf';const SCHOOL_EDITION=true;
const $=id=>document.getElementById(id);
const state={session:null,user:null,account:{},entitlements:[],promoAccesses:[],audience:'boys',logo:null,phraseIndex:0};
const NAV_ROUTES={results_analysis:{label:'تحليل النتائج',href:'../analysis/index.html'},guidance_records:{label:'السجلات الرقمية',href:'../records/index.html'},presentations:{label:'العروض التقديمية',href:'../presentations/index.html'},counselor_plan:{label:'خطة الموجه',href:'../plans/index.html'},achievement_reports:{label:'تقارير الإنجاز',href:'../reports/index.html'}};
const NAV_ICONS={results_analysis:'<svg viewBox="0 0 24 24"><path d="M4 19V9M10 19V5M16 19v-7M22 19H2"/></svg>',guidance_records:'<svg viewBox="0 0 24 24"><path d="M6 3h9l3 3v15H6z"/><path d="M15 3v4h4M9 11h6M9 15h6"/></svg>',presentations:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="12" rx="2"/><path d="M8 21l4-5 4 5M8 9h3M8 12h7"/></svg>',counselor_plan:'<svg viewBox="0 0 24 24"><path d="M6 3h12v18H6z"/><path d="M9 7h6M9 11h6M9 15h3"/><path d="m15 16 1.4 1.4L19 14.8"/></svg>',achievement_reports:'<svg viewBox="0 0 24 24"><path d="M5 3h14v18H5z"/><path d="M8 8h8M8 12h8M8 16h5"/></svg>'};

const CATEGORIES={
 excellence:{label:'شهادة تفوق',kicker:'تفوق يستحق الاحتفاء',occasions:[
  {id:'academic',label:'التفوق الدراسي العام',phrases:{boys:['تقديرًا لتفوقه الدراسي المشرّف، وما أظهره من جدٍ واجتهادٍ وطموحٍ متواصل، سائلين الله له دوام النجاح ومزيدًا من التميز.','إشادةً بما حققه من مستوى دراسي رفيع، وبما جسّده من مثابرة ومسؤولية ورغبة صادقة في صناعة مستقبل متميز.','فخرًا بإنجازه الأكاديمي اللافت، وتقديرًا لجهده الذي أثمر تفوقًا يبعث على الاعتزاز ويستحق كل الإشادة.'],girls:['تقديرًا لتفوقها الدراسي المشرّف، وما أظهرته من جدٍ واجتهادٍ وطموحٍ متواصل، سائلين الله لها دوام النجاح ومزيدًا من التميز.','إشادةً بما حققته من مستوى دراسي رفيع، وبما جسّدته من مثابرة ومسؤولية ورغبة صادقة في صناعة مستقبل متميز.','فخرًا بإنجازها الأكاديمي اللافت، وتقديرًا لجهدها الذي أثمر تفوقًا يبعث على الاعتزاز ويستحق كل الإشادة.']}},
  {id:'first',label:'المركز الأول / أحد الأوائل',phrases:{boys:['احتفاءً بحصوله على مركز متقدم بين زملائه، وتتويجًا لرحلة من الاجتهاد والانضباط والطموح نحو القمة.','تقديرًا لتميزه وحصوله على مكانة متقدمة في التحصيل الدراسي، متمنين له أن يظل التفوق عنوانًا لمسيرته.'],girls:['احتفاءً بحصولها على مركز متقدم بين زميلاتها، وتتويجًا لرحلة من الاجتهاد والانضباط والطموح نحو القمة.','تقديرًا لتميزها وحصولها على مكانة متقدمة في التحصيل الدراسي، متمنين لها أن يظل التفوق عنوانًا لمسيرتها.']}},
  {id:'subject',label:'التميز في مادة دراسية',phrases:{boys:['تقديرًا لتميزه اللافت في المادة الدراسية، وما أظهره من فهم عميق ومثابرة جعلت أداءه نموذجًا يُحتذى.','إشادةً بإنجازه المتميز في المادة، وحرصه على التعلم والإتقان والمشاركة الإيجابية.'],girls:['تقديرًا لتميزها اللافت في المادة الدراسية، وما أظهرته من فهم عميق ومثابرة جعلت أداءها نموذجًا يُحتذى.','إشادةً بإنجازها المتميز في المادة، وحرصها على التعلم والإتقان والمشاركة الإيجابية.']}},
  {id:'abilities',label:'التميز في القدرات والتحصيلي',phrases:{boys:['تقديرًا لنتيجته المتميزة في اختبارات القدرات والتحصيلي، وثمرةً لاستعداده المنظم وطموحه العالي نحو مستقبله الجامعي.','إشادةً بجديته في الاستعداد للقدرات والتحصيلي وما حققه من تقدم يعكس عزيمته وإدارته الواعية لأهدافه.'],girls:['تقديرًا لنتيجتها المتميزة في اختبارات القدرات والتحصيلي، وثمرةً لاستعدادها المنظم وطموحها العالي نحو مستقبلها الجامعي.','إشادةً بجديتها في الاستعداد للقدرات والتحصيلي وما حققته من تقدم يعكس عزيمتها وإدارتها الواعية لأهدافها.']}},
  {id:'improvement',label:'التحسن الدراسي الملحوظ',phrases:{boys:['تقديرًا للتحسن الملحوظ الذي حققه، وما أبداه من إصرار على تجاوز التحديات وتحويل الجهد إلى تقدم حقيقي يستحق الإشادة.','احتفاءً بتقدمه الدراسي المميز، وبرهانًا على أن المثابرة والاستمرار يصنعان فارقًا يستحق الفخر.'],girls:['تقديرًا للتحسن الملحوظ الذي حققته، وما أبدته من إصرار على تجاوز التحديات وتحويل الجهد إلى تقدم حقيقي يستحق الإشادة.','احتفاءً بتقدمها الدراسي المميز، وبرهانًا على أن المثابرة والاستمرار يصنعان فارقًا يستحق الفخر.']}},
  {id:'attendance',label:'التفوق في الحضور والمواظبة',phrases:{boys:['تقديرًا لالتزامه المتميز بالحضور والمواظبة والانضباط، وما يمثله ذلك من وعي ومسؤولية واحترام لقيمة الوقت.'],girls:['تقديرًا لالتزامها المتميز بالحضور والمواظبة والانضباط، وما يمثله ذلك من وعي ومسؤولية واحترام لقيمة الوقت.']}}
 ]},
 appreciation:{label:'شهادة تقدير',kicker:'تقديرٌ لسلوكٍ يصنع الفرق',occasions:[
  {id:'behavior',label:'التميز السلوكي',phrases:{boys:['تقديرًا لتميزه السلوكي وأخلاقه الرفيعة، وما يتحلى به من احترام وتعاون ومسؤولية تجعله قدوة إيجابية بين زملائه.','عرفانًا بحسن سلوكه ورقي تعامله والتزامه بالقيم التي تعكس شخصية طالب واعٍ ومتميز.','إشادةً بسلوكه الإيجابي المستمر، ومواقفه التي تنشر الاحترام واللطف والانضباط في البيئة المدرسية.'],girls:['تقديرًا لتميزها السلوكي وأخلاقها الرفيعة، وما تتحلى به من احترام وتعاون ومسؤولية تجعلها قدوة إيجابية بين زميلاتها.','عرفانًا بحسن سلوكها ورقي تعاملها والتزامها بالقيم التي تعكس شخصية طالبة واعية ومتميزة.','إشادةً بسلوكها الإيجابي المستمر، ومواقفها التي تنشر الاحترام واللطف والانضباط في البيئة المدرسية.']}},
  {id:'discipline',label:'الانضباط والمواظبة',phrases:{boys:['تقديرًا لانضباطه ومواظبته وحرصه على الالتزام بأنظمة المدرسة ومواعيدها، بما يعكس حسًا عاليًا بالمسؤولية.'],girls:['تقديرًا لانضباطها ومواظبتها وحرصها على الالتزام بأنظمة المدرسة ومواعيدها، بما يعكس حسًا عاليًا بالمسؤولية.']}},
  {id:'leadership',label:'القيادة والمبادرة',phrases:{boys:['تقديرًا لروحه القيادية ومبادرته الإيجابية، وقدرته على التأثير الحسن والعمل بروح الفريق وتحمل المسؤولية.','إشادةً بمبادرته وحضوره القيادي المتميز، وما يقدمه من نموذج في الثقة والمسؤولية وخدمة الآخرين.'],girls:['تقديرًا لروحها القيادية ومبادرتها الإيجابية، وقدرتها على التأثير الحسن والعمل بروح الفريق وتحمل المسؤولية.','إشادةً بمبادرتها وحضورها القيادي المتميز، وما تقدمه من نموذج في الثقة والمسؤولية وخدمة الآخرين.']}},
  {id:'volunteer',label:'العمل التطوعي وخدمة المدرسة',phrases:{boys:['شكرًا وتقديرًا لعطائه التطوعي ومشاركته الفاعلة في خدمة المدرسة، وإسهامه بروح إيجابية تعكس قيمة العطاء والمسؤولية المجتمعية.'],girls:['شكرًا وتقديرًا لعطائها التطوعي ومشاركتها الفاعلة في خدمة المدرسة، وإسهامها بروح إيجابية تعكس قيمة العطاء والمسؤولية المجتمعية.']}},
  {id:'creativity',label:'الإبداع والابتكار',phrases:{boys:['تقديرًا لإبداعه وتميز أفكاره، وقدرته على تقديم حلول ومشاركات تعكس خيالًا واسعًا وروحًا محبة للتجربة والتطوير.'],girls:['تقديرًا لإبداعها وتميز أفكارها، وقدرتها على تقديم حلول ومشاركات تعكس خيالًا واسعًا وروحًا محبة للتجربة والتطوير.']}},
  {id:'participation',label:'المشاركة المدرسية المتميزة',phrases:{boys:['شكرًا لمشاركته الفاعلة وحضوره الإيجابي في أنشطة المدرسة، وما أضافه من تعاون وحماس أسهما في نجاح العمل.'],girls:['شكرًا لمشاركتها الفاعلة وحضورها الإيجابي في أنشطة المدرسة، وما أضافته من تعاون وحماس أسهما في نجاح العمل.']}},
  {id:'responsibility',label:'تحمل المسؤولية والقدوة الحسنة',phrases:{boys:['تقديرًا لما يتحلى به من مسؤولية واعية وقدوة حسنة، وحرصه على أداء واجباته والتعامل بإيجابية واحترام.'],girls:['تقديرًا لما تتحلى به من مسؤولية واعية وقدوة حسنة، وحرصها على أداء واجباتها والتعامل بإيجابية واحترام.']}}
 ]},
 congratulations:{label:'شهادة تهنئة',kicker:'فرحةٌ بإنجاز يستحق التهنئة',occasions:[
  {id:'success',label:'النجاح والانتقال للمرحلة التالية',phrases:{boys:['بمناسبة نجاحه المستحق، يسر التوجيه الطلابي أن يشاركه فرحة الإنجاز ويتمنى له مرحلة قادمة مليئة بالطموح والنجاحات.','تهنئة صادقة بنجاحه، مع أمنياتنا بأن يكون هذا الإنجاز بداية لمسيرة أوسع من التميز والتقدم.'],girls:['بمناسبة نجاحها المستحق، يسر التوجيه الطلابي أن يشاركها فرحة الإنجاز ويتمنى لها مرحلة قادمة مليئة بالطموح والنجاحات.','تهنئة صادقة بنجاحها، مع أمنياتنا بأن يكون هذا الإنجاز بداية لمسيرة أوسع من التميز والتقدم.']}},
  {id:'program',label:'التكريم ضمن أحد البرامج',phrases:{boys:['تقديرًا لمشاركته المتميزة واستحقاقه التكريم ضمن برنامج «{program}»، وما قدمه من تفاعل إيجابي يعكس روح المبادرة والتميز.','احتفاءً بتميزه في برنامج «{program}»، وإشادةً بمشاركته التي أسهمت في نجاح البرنامج وتحقيق أهدافه.'],girls:['تقديرًا لمشاركتها المتميزة واستحقاقها التكريم ضمن برنامج «{program}»، وما قدمته من تفاعل إيجابي يعكس روح المبادرة والتميز.','احتفاءً بتميزها في برنامج «{program}»، وإشادةً بمشاركتها التي أسهمت في نجاح البرنامج وتحقيق أهدافه.']}},
  {id:'competition',label:'الفوز في مسابقة أو تحدٍ',phrases:{boys:['تهنئةً بفوزه المتميز في المسابقة، وتقديرًا لجهده وروحه التنافسية الإيجابية التي قادته إلى هذا الإنجاز المستحق.'],girls:['تهنئةً بفوزها المتميز في المسابقة، وتقديرًا لجهدها وروحها التنافسية الإيجابية التي قادتها إلى هذا الإنجاز المستحق.']}},
  {id:'completion',label:'إتمام برنامج أو مبادرة',phrases:{boys:['تهنئةً بإتمامه برنامج «{program}» بنجاح، وتقديرًا لالتزامه وتفاعله واستفادته الإيجابية طوال فترة التنفيذ.'],girls:['تهنئةً بإتمامها برنامج «{program}» بنجاح، وتقديرًا لالتزامها وتفاعلها واستفادتها الإيجابية طوال فترة التنفيذ.']}},
  {id:'positive_change',label:'تحول إيجابي يستحق التكريم',phrases:{boys:['احتفاءً بالتغيير الإيجابي الملحوظ في أدائه وسلوكه، وتقديرًا لشجاعته في التطور واستمراره في بناء نسخة أفضل من ذاته.'],girls:['احتفاءً بالتغيير الإيجابي الملحوظ في أدائها وسلوكها، وتقديرًا لشجاعتها في التطور واستمرارها في بناء نسخة أفضل من ذاتها.']}},
  {id:'graduation',label:'التخرج وإتمام المرحلة',phrases:{boys:['بكل الفخر نهنئه بإتمام مرحلته الدراسية، ونتمنى له مستقبلًا يليق بطموحه، وخطوات قادمة يرافقها النجاح والتوفيق.'],girls:['بكل الفخر نهنئها بإتمام مرحلتها الدراسية، ونتمنى لها مستقبلًا يليق بطموحها، وخطوات قادمة يرافقها النجاح والتوفيق.']}}
 ]}
};

const PARENT_MESSAGES={
 excellence:{boys:['كما يسر التوجيه الطلابي أن يهنئ ولي أمر الطالب الكريم، ويثمّن دعمه ومتابعته التي كان لها أثرٌ واضح في هذا التفوق.','وتمتد التهنئة إلى أسرته الكريمة؛ فخلف كل إنجاز عظيم دعمٌ ومتابعة وصناعة ثقة تستحق التقدير.'],girls:['كما يسر التوجيه الطلابي أن يهنئ ولي أمر الطالبة الكريم، ويثمّن دعمه ومتابعته التي كان لها أثرٌ واضح في هذا التفوق.','وتمتد التهنئة إلى أسرتها الكريمة؛ فخلف كل إنجاز عظيم دعمٌ ومتابعة وصناعة ثقة تستحق التقدير.']},
 appreciation:{boys:['كما نتقدم لولي أمر الطالب بخالص التقدير والتهنئة، شاكرين للأسرة دورها في ترسيخ القيم والسلوك الإيجابي.','وإلى أسرته الكريمة نهدي هذه التهنئة، تقديرًا لما غرسته من قيم انعكست تميزًا وسلوكًا مشرفًا.'],girls:['كما نتقدم لولي أمر الطالبة بخالص التقدير والتهنئة، شاكرين للأسرة دورها في ترسيخ القيم والسلوك الإيجابي.','وإلى أسرتها الكريمة نهدي هذه التهنئة، تقديرًا لما غرسته من قيم انعكست تميزًا وسلوكًا مشرفًا.']},
 congratulations:{boys:['ونشارك ولي أمر الطالب فرحة هذا الإنجاز، مع خالص الشكر للأسرة على دعمها وتشجيعها المستمر.','كما نبارك لأسرته الكريمة هذا الإنجاز، متمنين أن تتجدد الأفراح مع كل خطوة نجاح قادمة.'],girls:['ونشارك ولي أمر الطالبة فرحة هذا الإنجاز، مع خالص الشكر للأسرة على دعمها وتشجيعها المستمر.','كما نبارك لأسرتها الكريمة هذا الإنجاز، متمنين أن تتجدد الأفراح مع كل خطوة نجاح قادمة.']}
};

function safeParse(raw){try{return JSON.parse(raw)}catch(_e){return null}}
function deepFindSession(value,depth=0){if(depth>6||value==null)return null;if(typeof value==='string'){let text=value;if(text.startsWith('base64-')){try{text=decodeURIComponent(escape(atob(text.slice(7).replace(/-/g,'+').replace(/_/g,'/'))))}catch(_e){}}const p=safeParse(text);return p?deepFindSession(p,depth+1):null}if(Array.isArray(value)){for(const item of value){const f=deepFindSession(item,depth+1);if(f)return f}return null}if(typeof value==='object'){if(value.access_token&&value.refresh_token)return value;for(const key of ['currentSession','session','data','value']){if(value[key]){const f=deepFindSession(value[key],depth+1);if(f)return f}}for(const key of Object.keys(value)){const f=deepFindSession(value[key],depth+1);if(f)return f}}return null}
function findSession(){const preferred=`sb-${PROJECT_REF}-auth-token`;for(const store of [localStorage,sessionStorage]){let keys=[];try{for(let i=0;i<store.length;i++){const k=store.key(i);if(k)keys.push(k)}}catch(_e){}keys.sort((a,b)=>(a===preferred?-1:0)-(b===preferred?-1:0));for(const key of keys){if(!key.startsWith('sb-')||!key.includes('auth-token'))continue;const s=deepFindSession(store.getItem(key));if(s)return{session:s,store,key}}}return null}
function timeout(p,ms=12000){return Promise.race([p,new Promise((_,rej)=>setTimeout(()=>rej(new Error('network_timeout')),ms))])}
async function api(path,opt={}){const headers={apikey:SUPABASE_KEY,Accept:'application/json'};if(opt.token)headers.Authorization='Bearer '+opt.token;if(opt.body!==undefined)headers['Content-Type']='application/json';const r=await timeout(fetch(SUPABASE_URL+path,{method:opt.method||'GET',headers,body:opt.body===undefined?undefined:JSON.stringify(opt.body),cache:'no-store'}));const t=await r.text();const d=t?safeParse(t):null;if(!r.ok){const e=new Error(d?.message||d?.error_description||`http_${r.status}`);e.status=r.status;throw e}return d}
async function verify(found){let active=found.session;try{const user=await api('/auth/v1/user',{token:active.access_token});return{session:active,user}}catch(e){if(e.status!==401||!active.refresh_token)throw e;const fresh=await api('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:active.refresh_token}});try{found.store.setItem(found.key,JSON.stringify(fresh))}catch(_e){}const user=await api('/auth/v1/user',{token:fresh.access_token});return{session:fresh,user}}}
function activeEntitlements(){return state.entitlements.filter(e=>e&&e.is_active!==false&&new Date(e.expires_at).getTime()>Date.now())}
function activePromos(){return state.promoAccesses.filter(p=>p&&new Date(p.access_ends_at).getTime()>Date.now())}
function hasGiftAccess(){return true}
function navHasAccess(code){return true}
function renderUnifiedNav(){const bar=$('unifiedPlatformBar'),box=$('platformSwitcher'),badge=$('platformPlanBadge');box.innerHTML=Object.keys(NAV_ROUTES).map(code=>{const item=NAV_ROUTES[code],icon=NAV_ICONS[code];return navHasAccess(code)?`<a class="platform-tab" href="${item.href}?from=portal"><span class="platform-tab-icon">${icon}</span><span class="platform-tab-copy"><strong>${item.label}</strong><small>انتقال إلى المنصة</small></span></a>`:`<span class="platform-tab locked"><span class="platform-tab-icon">${icon}</span><span class="platform-tab-copy"><strong>${item.label}</strong><small>غير مفعّلة</small></span></span>`}).join('');badge.innerHTML='<span class="platform-plan-status"></span><span class="platform-plan-copy"><span>المنصة الحالية</span><strong>شهادات التقدير</strong><small>متاحة للمدرسة</small></span>';bar.hidden=false}
function gateError(title,msg){$('gateSpinner').hidden=true;$('gateIcon').hidden=false;$('gateTitle').textContent=title;$('gateMessage').textContent=msg;$('gateActions').hidden=false}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(msg){$('toast').textContent=msg;$('toast').hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').hidden=true,2600)}
function formatDate(v){if(!v)return'';const d=new Date(v+'T12:00:00');return Number.isNaN(d.getTime())?v:d.toLocaleDateString('ar-SA',{year:'numeric',month:'long',day:'numeric'})}
function serialFor(name){let h=0;const s=(name||'STUDENT')+($('dateInput').value||'');for(let i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return 'SG-'+($('dateInput').value||new Date().toISOString().slice(0,10)).replaceAll('-','')+'-'+Math.abs(h).toString(36).toUpperCase().slice(0,5).padStart(5,'0')}
function currentCategory(){return CATEGORIES[$('categorySelect').value]||CATEGORIES.excellence}
function currentOccasion(){const cat=currentCategory();return cat.occasions.find(o=>o.id===$('occasionSelect').value)||cat.occasions[0]}
function phraseText(){const o=currentOccasion();const list=o.phrases[state.audience]||o.phrases.boys;const p=list[state.phraseIndex%list.length]||list[0];return p.replaceAll('{program}',($('programInput').value||'البرنامج المدرسي').trim())}
function parentMessage(){const cat=$('categorySelect').value;const list=PARENT_MESSAGES[cat][state.audience];return list[state.phraseIndex%list.length]}
function fillOccasions(){const cat=currentCategory();$('occasionSelect').innerHTML=cat.occasions.map(o=>`<option value="${o.id}">${esc(o.label)}</option>`).join('');state.phraseIndex=0;updatePhraseFields()}
function updatePhraseFields(){const occ=currentOccasion();$('bodyInput').value=phraseText();$('parentMessageInput').value=parentMessage();$('programLabel').hidden=!['program','completion'].includes(occ.id);$('certificateTypeLabel').textContent=currentCategory().label;render()}
function adaptParentLine(text){const parent=($('parentNameInput').value||'').trim();if(!parent)return text;const who=state.audience==='girls'?'ولي أمر الطالبة':'ولي أمر الطالب';return text.replace(who,parent?`${who}: ${parent}`:who)}
function certificateDirectory(){return (window.MishkatSchoolDirectory||window.MishkatBubbleDirectory)?.getSnapshot?.()||{students:[]}}
function certStudentById(id){return (certificateDirectory().students||[]).find(s=>String(s.id)===String(id))||null}
function selectedCertStudent(){return certStudentById($('studentNameInput').value)}
function studentNameFromSelect(){return selectedCertStudent()?.name||''}
async function loadCertificateStudents(){
  const dir=window.MishkatSchoolDirectory||window.MishkatBubbleDirectory;
  try{if(dir?.load)await dir.load()}catch(e){console.warn('Certificate student directory unavailable',e)}
  const rows=certificateDirectory().students||[];
  const current=$('studentNameInput').value;
  $('studentNameInput').innerHTML='<option value="">اختر الطالب</option>'+rows.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');
  $('batchInput').innerHTML=rows.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}${s.grade||s.className?` — ${esc([s.grade,s.className].filter(Boolean).join(' / '))}`:''}</option>`).join('');
  if(rows.some(s=>String(s.id)===String(current)))$('studentNameInput').value=current;
  const apply=()=>{const st=selectedCertStudent();$('classInput').value=st?.grade||'';$('sectionInput').value=st?.className||'';render()};
  $('studentNameInput').onchange=apply;apply();
}
function certificateData(override={}){const ctx=window.MishkatSchoolContext?.getContext?.()||{};const selected=selectedCertStudent();const studentId=override.studentId||selected?.id||$('studentNameInput').value||'';const student=override.student||selected?.name||'';return{studentId,student:student||(state.audience==='girls'?'اسم الطالبة':'اسم الطالب'),className:override.className??selected?.grade??$('classInput').value.trim(),section:override.section??selected?.className??$('sectionInput').value.trim(),school:ctx.schoolName||$('schoolInput').value.trim()||'اسم المدرسة',counselor:ctx.counselorName||$('counselorInput').value.trim()||'الموجه الطلابي',director:ctx.managerName||$('directorInput').value.trim()||'مدير المدرسة',date:$('dateInput').value,year:ctx.academicYear||$('yearInput').value.trim(),achievement:$('achievementInput').value.trim(),body:$('bodyInput').value.trim(),parent:adaptParentLine($('parentMessageInput').value.trim()),category:currentCategory(),occasion:currentOccasion(),design:$('designSelect').value,logo:state.logo,serial:serialFor(student),showSerial:$('showSerialInput').checked,showClass:$('showClassInput').checked}}
function certHTML(d){const initial=(d.school||'م').trim().charAt(0)||'م';const detail=[d.showClass&&d.className?`الصف: ${d.className}`:'',d.showClass&&d.section?`الفصل: ${d.section}`:'',d.achievement].filter(Boolean).join(' · ');const logo=d.logo?`<img class="cert-logo" src="${d.logo}" alt="شعار المدرسة">`:`<div class="cert-logo-placeholder">${esc(initial)}</div>`;return `<div class="certificate design-${esc(d.design)}"><div class="cert-ribbon">التوجيه الطلابي</div><i class="cert-corner corner-a"></i><i class="cert-corner corner-b"></i><div class="cert-inner"><div class="cert-top">${logo}<div class="cert-school"><span>${esc(d.school)}</span><strong>التوجيه الطلابي</strong></div><div class="cert-dept"><b>تكريم وتميّز</b><small>${esc(d.year||'')}</small></div></div><div class="cert-icon">★</div><div class="cert-kicker">${esc(d.category.kicker)}</div><div class="cert-title">${esc(d.category.label)}</div><div class="cert-presents">يُسر التوجيه الطلابي أن يقدّم هذه الشهادة إلى</div><div class="cert-student">${esc(d.student)}</div><p class="cert-body">${esc(d.body)}</p>${detail?`<div class="cert-detail">${esc(detail)}</div>`:''}<div class="cert-parent">${esc(d.parent)}</div><div class="cert-signatures"><div class="signature"><span>الموجه الطلابي</span><strong>${esc(d.counselor)}</strong><i class="signature-line"></i></div><div class="signature"><span>مدير المدرسة</span><strong>${esc(d.director)}</strong><i class="signature-line"></i></div></div><div class="cert-footer"><span>${esc(formatDate(d.date))}</span>${d.showSerial?`<span class="cert-serial">${esc(d.serial)}</span>`:'<span></span>'}</div></div></div>`}
function render(){const d=certificateData();$('certificatePreview').outerHTML=certHTML(d).replace('<div class="certificate','<div id="certificatePreview" class="certificate') ;saveLocal()}
function saveLocal(){try{localStorage.setItem('certificates_v19_form',JSON.stringify({category:$('categorySelect').value,occasion:$('occasionSelect').value,program:$('programInput').value,body:$('bodyInput').value,parentMessage:$('parentMessageInput').value,studentId:$('studentNameInput').value,achievement:$('achievementInput').value,parentName:$('parentNameInput').value,date:$('dateInput').value,design:$('designSelect').value,showSerial:$('showSerialInput').checked,showClass:$('showClassInput').checked,batchIds:Array.from($('batchInput').selectedOptions).map(o=>o.value)}))}catch(_e){}}
function restoreLocal(){const d=safeParse(localStorage.getItem('certificates_v19_form'))||safeParse(localStorage.getItem('certificates_v18_form'));if(!d)return false;$('categorySelect').value=d.category||'excellence';fillOccasions();if(d.occasion&&Array.from($('occasionSelect').options).some(o=>o.value===d.occasion))$('occasionSelect').value=d.occasion;[['programInput','program'],['bodyInput','body'],['parentMessageInput','parentMessage'],['achievementInput','achievement'],['parentNameInput','parentName'],['dateInput','date'],['designSelect','design']].forEach(([id,key])=>{if(d[key]!=null)$(id).value=d[key]});if(d.studentId)$('studentNameInput').value=d.studentId;if(Array.isArray(d.batchIds)){Array.from($('batchInput').options).forEach(o=>o.selected=d.batchIds.includes(o.value));}$('showSerialInput').checked=d.showSerial!==false;$('showClassInput').checked=d.showClass!==false;return true}
function parseBatch(){return Array.from($('batchInput').selectedOptions).map(opt=>{const st=certStudentById(opt.value);return{studentId:st?.id||opt.value,student:st?.name||opt.textContent,className:st?.grade||'',section:st?.className||''}})}
function certificateStudentId(name){const rows=window.MishkatSchoolContext?.getStudents?.()||[];const n=String(name||'').trim();const row=rows.find(s=>String(s?.['Full Name']||s?.full_name||s?.name||'').trim()===n);return window.MishkatBubbleStore?.idOf?.(row)||''}
function persistCertificateIssue(d){if(!window.MishkatBubbleStore)return Promise.resolve();return window.MishkatBubbleStore.saveCertificateModel({studentId:d.studentId||certificateStudentId(d.student),studentName:d.student,certificateType:d.category?.id||d.category?.label||'certificate',reason:d.achievement||d.body,issueDate:d.date,certificateNumber:d.serial,notes:d.parent||''}).catch(e=>console.warn('Certificate save fallback',e))}
function printItems(items){const docs=items.map(x=>certificateData(x));$('printRoot').innerHTML=docs.map(certHTML).join('');Promise.allSettled(docs.map(persistCertificateIssue));setTimeout(()=>window.print(),80)}
function compressLogo(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=700,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/png'))};img.src=r.result};r.readAsDataURL(file)})}
function populatePrograms(){const list=Array.isArray(window.REPORT_PROGRAMS)?window.REPORT_PROGRAMS:[];$('programSuggestions').innerHTML=list.map(p=>`<option value="${esc(p.title)}"></option>`).join('')}
function wire(){populatePrograms();$('categorySelect').onchange=fillOccasions;$('occasionSelect').onchange=()=>{state.phraseIndex=0;updatePhraseFields()};$('nextPhraseButton').onclick=()=>{state.phraseIndex++;updatePhraseFields()};['programInput','bodyInput','parentMessageInput','studentNameInput','classInput','sectionInput','achievementInput','parentNameInput','schoolInput','counselorInput','directorInput','dateInput','yearInput','designSelect','showSerialInput','showClassInput'].forEach(id=>$(id).addEventListener(['SELECT','INPUT','TEXTAREA'].includes($(id).tagName)?'input':'change',()=>{if(id==='programInput'&&['program','completion'].includes(currentOccasion().id))$('bodyInput').value=phraseText();render()}));$('designSelect').onchange=render;$('showSerialInput').onchange=render;$('showClassInput').onchange=render;$('batchInput').onchange=saveLocal;$('logoInput').onchange=function(){const f=this.files[0];if(!f)return;compressLogo(f).then(src=>{state.logo=src;render();toast('تم تحديث شعار المدرسة')}).catch(()=>toast('تعذر قراءة الشعار'))};$('printCurrentButton').onclick=()=>printItems([{}]);$('printBatchButton').onclick=()=>{const list=parseBatch();if(!list.length)return toast('اختر الطلاب من قسم الإصدار الجماعي أولًا');printItems(list)};$('resetButton').onclick=()=>{if(!confirm('بدء شهادة جديدة مع الاحتفاظ ببيانات المدرسة؟'))return;$('studentNameInput').value='';$('classInput').value='';$('sectionInput').value='';$('achievementInput').value='';$('parentNameInput').value='';Array.from($('batchInput').options).forEach(o=>o.selected=false);state.phraseIndex=0;updatePhraseFields();toast('تم فتح شهادة جديدة')};$('retryButton').onclick=()=>location.reload()}
async function boot(){
  if(SCHOOL_EDITION){const ctx=window.MishkatSchoolContext?.getContext?.()||{};state.session=null;state.user={id:ctx.id||'mishkat-school-user',email:''};state.account={full_name:ctx.counselorName||'الموجه الطلابي',school_name:ctx.schoolName||'مدارس المشكاة الأهلية',school_logo_data:null,is_system_admin:false,is_active:true,presentation_audience_type:ctx.schoolType==='girls'?'girls':'boys'};state.entitlements=[];state.promoAccesses=[];state.audience=state.account.presentation_audience_type==='girls'?'girls':'boys';state.logo=null;$('audienceBadge').textContent=state.audience==='girls'?'شهادات الطالبات':'شهادات الطلاب';$('schoolInput').value=ctx.schoolName||state.account.school_name;$('counselorInput').value=ctx.counselorName||state.account.full_name;$('directorInput').value=ctx.managerName||'';$('yearInput').value=ctx.academicYear||$('yearInput').value;$('dateInput').value=new Date().toISOString().slice(0,10);fillOccasions();const studentLoad=Promise.race([loadCertificateStudents(),new Promise(resolve=>setTimeout(resolve,5000))]).catch(error=>console.warn("Certificate students load failed",error));const restored=restoreLocal();if(!restored)updatePhraseFields();else{const st=selectedCertStudent();$('classInput').value=st?.grade||'';$('sectionInput').value=st?.className||'';}renderUnifiedNav();wire();render();$('gate').hidden=true;$('app').hidden=false;studentLoad.then(()=>{try{render()}catch(_e){}});return;}
  const found=findSession();if(!found){gateError('يلزم تسجيل الدخول','ارجع إلى البوابة الرئيسية وسجّل الدخول، ثم افتح منصة شهادات التقدير من داخل البوابة.');return}try{const r=await verify(found);state.session=r.session;state.user=r.user;const nowIso=new Date().toISOString();const [acc,ents,promos]=await Promise.all([api('/rest/v1/premium_accounts?select=full_name,school_name,school_logo_data,is_system_admin,is_active,presentation_audience_type&user_id=eq.'+encodeURIComponent(r.user.id)+'&limit=1',{token:r.session.access_token}),api('/rest/v1/premium_entitlements?select=product_code,billing_period,expires_at,is_active&user_id=eq.'+encodeURIComponent(r.user.id),{token:r.session.access_token}),api('/rest/v1/premium_promo_redemptions?select=product_code,access_ends_at&user_id=eq.'+encodeURIComponent(r.user.id)+'&access_ends_at=gt.'+encodeURIComponent(nowIso),{token:r.session.access_token}).catch(()=>[])]);state.account=Array.isArray(acc)?(acc[0]||{}):{};state.entitlements=Array.isArray(ents)?ents:[];state.promoAccesses=Array.isArray(promos)?promos:[];if(state.account.is_active===false){gateError('الحساب موقوف','تواصل مع مدير النظام لإعادة تفعيل الحساب.');return}state.audience=state.account.presentation_audience_type==='girls'?'girls':'boys';state.logo=state.account.school_logo_data||null;$('audienceBadge').textContent=state.audience==='girls'?'شهادات الطالبات':'شهادات الطلاب';const ctx=window.MishkatSchoolContext?.getContext?.()||{};$('schoolInput').value=ctx.schoolName||state.account.school_name||'';$('counselorInput').value=ctx.counselorName||state.account.full_name||'';$('directorInput').value=ctx.managerName||'';$('yearInput').value=ctx.academicYear||$('yearInput').value;$('dateInput').value=new Date().toISOString().slice(0,10);fillOccasions();const restored=restoreLocal();if(restored){if(!state.logo&&state.account.school_logo_data)state.logo=state.account.school_logo_data}else{updatePhraseFields()}renderUnifiedNav();wire();render();$('gate').hidden=true;$('app').hidden=false}catch(e){console.error(e);gateError('تعذر فتح المنصة',e.message==='network_timeout'?'استغرقت خدمة التحقق وقتًا أطول من المعتاد. اضغط إعادة المحاولة.':'انتهت الجلسة أو تعذر الاتصال. ارجع إلى البوابة وسجّل الدخول مرة أخرى.')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
