"use strict";

const SUPABASE_URL="https://fpicgtldwfevdvpbxkjf.supabase.co";
const SUPABASE_KEY="sb_publishable_3C7eKHRkzE2T-OLOpfue4g_i3u4R7Ay";
const CURRENT_PACKAGE_CODE="counselor_plan";
const db=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
window.__UNIFIED_PLATFORM_DB__=db;

const PACKAGE_LABELS={results_analysis:"باقة تحليل النتائج",guidance_records:"باقة السجلات الرقمية",presentations:"باقة العروض التقديمية",counselor_plan:"باقة خطة الموجه الطلابي",achievement_reports:"منصة تقارير الإنجاز",messages_library:"مكتبة رسائل أولياء الأمور",all_access:"الباقة الشاملة"};
const UNIFIED_PLATFORM_ROUTES={
  results_analysis:{label:"تحليل النتائج",href:"../analysis/index.html"},
  guidance_records:{label:"السجلات الرقمية",href:"../records/index.html"},
  presentations:{label:"العروض التقديمية",href:"../presentations/index.html"},
  counselor_plan:{label:"خطة الموجه",href:"../plans/index.html"},
  achievement_reports:{label:"تقارير الإنجاز",href:"../reports/index.html"},
  messages_library:{label:"مراسلات ولي الأمر",href:"../messages/index.html"}
};
const UNIFIED_PLATFORM_ICONS={
  results_analysis:'<svg viewBox="0 0 24 24"><path d="M4 19V9M10 19V5M16 19v-7M22 19H2"/></svg>',
  guidance_records:'<svg viewBox="0 0 24 24"><path d="M6 3h9l3 3v15H6z"/><path d="M15 3v4h4M9 11h6M9 15h6"/></svg>',
  presentations:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="12" rx="2"/><path d="M8 21l4-5 4 5M8 9h3M8 12h7"/></svg>',
  counselor_plan:'<svg viewBox="0 0 24 24"><path d="M6 3h12v18H6z"/><path d="M9 7h6M9 11h6M9 15h3"/><path d="m15 16 1.4 1.4L19 14.8"/></svg>',
  achievement_reports:'<svg viewBox="0 0 24 24"><path d="M5 3h14v18H5z"/><path d="M8 8h8M8 12h8M8 16h5"/><path d="m15 17 1.5 1.5L20 15"/></svg>',
  messages_library:'<svg viewBox="0 0 24 24"><path d="M4 5h16v12H7l-3 3z"/><path d="M8 9h8M8 13h5"/></svg>'
};

const STAGES={
  lower_primary:{label:"الابتدائية الدنيا",audience:"طلاب الصفوف الأولية",focus:"تهيئة الطلاب للبيئة المدرسية وبناء العادات الأساسية الآمنة وتعزيز السلوك الإيجابي بلغة مبسطة ومواقف عملية قريبة من عمرهم.",extras:["متابعة تكيف الطلاب المستجدين مع البيئة المدرسية.","رصد الاحتياجات النمائية والسلوكية المبكرة والتنسيق مع المعلمين."],programs:[
    ["التهيئة النفسية واستقبال الطلاب","التعريف بخدمات التوجيه الطلابي"],["أنا أحب مدرستي","العادات المدرسية اليومية"],["النظافة الشخصية والعناية بالصحة","تنظيم الحقيبة والواجبات"],["الصداقة واحترام الآخرين","الكلمة الطيبة"],["برنامج رفق المبسط","الحماية من التنمر"],["التعامل مع المشاعر","كيف أطلب المساعدة؟"],["السلامة الرقمية المبسطة","المحافظة على الخصوصية"],["التعاون والمسؤولية","المحافظة على ممتلكات المدرسة"],["الانضباط والحضور المبكر","تعزيز السلوك الإيجابي"],["خصائص النمو للصفوف الأولية","التواصل مع الأسرة"],["إدارة الغضب بطريقة آمنة","حل الخلافات البسيطة"],["تنظيم الوقت والاستذكار","الاستعداد للتقويم والاختبارات"],["تكريم الطلاب المنضبطين","تعزيز الدافعية"],["العادات الغذائية الصحية","السلامة داخل المدرسة"],["العودة الإيجابية بعد الإجازة","تجديد الدافعية"],["متابعة الحالات الأولى بالرعاية","جلسات إرشاد فردية حسب الحاجة"],["تهيئة الطلاب لنهاية الفصل","المراجعة والاستعداد للاختبارات"],["متابعة الاختبارات وختام الفصل","تكريم التحسن والانضباط"]]},
  upper_primary:{label:"الابتدائية العليا",audience:"طلاب الصفوف العليا من المرحلة الابتدائية",focus:"دعم الانتقال النمائي لدى الطلاب وتعزيز المسؤولية والانضباط والمهارات الاجتماعية والرقمية والدافعية للتحصيل.",extras:["متابعة الطلاب ذوي التحصيل المنخفض ووضع تدخلات مبكرة.","تعزيز مهارات المسؤولية والانضباط والتواصل الإيجابي."],programs:[
    ["التهيئة النفسية واستقبال الطلاب","تحليل النتائج السابقة"],["خصائص النمو في المرحلة الابتدائية العليا","متابعة الطلاب الأولى بالرعاية"],["تعزيز السلوك الإيجابي","الانضباط المدرسي"],["برنامج رفق وخفض العنف","مواجهة التنمر"],["الاستخدام الآمن للإنترنت","المواطنة الرقمية"],["تنظيم الوقت والواجبات","مهارات الاستذكار"],["تنمية الدافعية لرفع التحصيل","خطة علاج الضعف الدراسي"],["إدارة الغضب وضبط الانفعال","فن التعامل مع الآخرين"],["الصحة النفسية وطلب المساعدة","الثقة بالنفس"],["التوعية بأضرار التدخين","اختيار الصحبة الإيجابية"],["المحافظة على الممتلكات","المسؤولية الشخصية"],["الاستعداد للاختبارات","التعامل مع قلق الاختبار"],["تكريم المتفوقين والمنضبطين","نشر الممارسات الإيجابية"],["التواصل مع أولياء الأمور","متابعة الخطط العلاجية"],["العودة بعد الإجازة وتجديد الدافعية","مراجعة أهداف الفصل"],["متابعة الحالات الخاصة","الإرشاد الفردي والجمعي"],["تهيئة الطلاب لنهاية الفصل","متابعة الاختبارات"],["تقويم برامج التوجيه","تكريم التحسن والإنجاز"]]},
  middle:{label:"المرحلة المتوسطة",audience:"طلاب المرحلة المتوسطة",focus:"مساندة الطلاب خلال مرحلة المراهقة المبكرة، وتنمية الوعي بالذات والسلوك المسؤول والدافعية للتحصيل والوقاية من المشكلات السلوكية والرقمية.",extras:["حصر الطلاب ذوي الحالات الخاصة والأولى بالرعاية وتحديث ملفاتهم.","متابعة المتأخرين دراسيًا والتنسيق مع الأسرة والمعلمين."],programs:[
    ["التهيئة النفسية واستقبال الطلاب","تحليل النتائج"],["متابعة الطلاب الأولى بالرعاية","ورشة تعريف ببرنامج تعزيز السلوك الإيجابي"],["تكريم المتفوقين","إدارة الغضب"],["برنامج خفض العنف رفق","الإرشاد وقت الأزمات"],["التوعية بأضرار التدخين — صفاء","الصحة النفسية"],["الأسبوع المكثف لبرنامج رفق","تعزيز السلوك الإيجابي"],["تنمية الدافعية لرفع المستوى التحصيلي","السلوك الإيجابي"],["خصائص النمو في المرحلة المتوسطة","رفع تقارير البرامج"],["الأسبوع المكثف للتوعية بأضرار التدخين","عرض الفعاليات لأولياء الأمور"],["تكريم المتميزين سلوكيًا","فن التعامل مع الآخرين"],["التهيئة النفسية للاختبارات","إدارة قلق الاختبار"],["تكريم المنضبطين","متابعة الخطط العلاجية"],["متابعة الاختبارات التحريرية","جلسات فردية حسب الحاجة"],["متابعة اختبارات نهاية الفصل","التواصل مع أولياء الأمور"],["العودة بعد الإجازة","تجديد الدافعية والانضباط"],["متابعة الحالات السابقة ومدى تحسنها","دراسة الحالات المستجدة"],["الاستعداد لنهاية الفصل","تنظيم الوقت والمراجعة"],["متابعة اختبارات نهاية الفصل","تقويم الخطة وختام الأعمال"]]},
  secondary:{label:"المرحلة الثانوية",audience:"طلاب المرحلة الثانوية",focus:"تمكين الطلاب من إدارة الضغوط واتخاذ القرار والتخطيط للمستقبل الدراسي والمهني، مع دعم الصحة النفسية والانضباط والوقاية من السلوكيات الخطرة.",extras:["متابعة المسار الدراسي والمهني للطلاب والتنسيق مع الجهات الداعمة.","رصد مؤشرات التعثر والضغط النفسي والتدخل المبكر وفق الإجراءات المهنية."],programs:[
    ["التهيئة النفسية واستقبال الطلاب","تحليل النتائج والتعثر الدراسي"],["التخطيط الدراسي وتحديد الأهداف","متابعة الطلاب الأولى بالرعاية"],["التوجيه المهني والميول","المسارات والتخصصات"],["القبول الجامعي والاختبارات المعيارية","بناء الملف الشخصي"],["إدارة الضغوط والصحة النفسية","طلب المساعدة والدعم"],["برنامج رفق وخفض العنف","إدارة النزاعات"],["الوقاية من التدخين والمخدرات","اختيار الصحبة"],["الأمن الرقمي والسمعة الإلكترونية","الاستخدام المسؤول للتقنية"],["تنمية الدافعية والتحصيل","مهارات الاستذكار المتقدم"],["اتخاذ القرار وحل المشكلات","تحمل المسؤولية"],["مهارات التواصل وفن التعامل","الذكاء العاطفي"],["الاستعداد للاختبارات","إدارة قلق الاختبار"],["تكريم المتفوقين والمنضبطين","نماذج نجاح طلابية"],["متابعة الخطط العلاجية","التواصل مع الأسرة والمعلمين"],["العودة بعد الإجازة","تجديد الأهداف الدراسية"],["خطط ما بعد الثانوية","الفرص التعليمية والمهنية"],["تهيئة الطلاب لنهاية الفصل","متابعة الاختبارات"],["تقويم البرامج وختام الفصل","توثيق الإنجازات والتوصيات"]]}
};

const COMMON_TASKS=[
  "استقبال الطلاب وأولياء الأمور في المدرسة.",
  "تنفيذ البرامج والخدمات الإرشادية حسب الجدول الزمني.",
  "استقبال الاتصالات والاستشارات الهاتفية.",
  "متابعة حالات الطلاب السابقة ومدى تحسنها.",
  "متابعة حالات بعض الطلاب الخاصة والمتأخرين دراسيًا.",
  "المشاركة في الدورات واللقاءات التي تقيمها الإدارة أو القسم."
];
const HOLIDAY_TYPES={term:"إجازة فصلية",extended:"إجازة مطولة",occasion:"إجازة مناسبة",official:"إجازة رسمية",other:"إجازة أخرى"};
const WEEK_ORDINALS=["الأول","الثاني","الثالث","الرابع","الخامس","السادس","السابع","الثامن","التاسع","العاشر","الحادي عشر","الثاني عشر","الثالث عشر","الرابع عشر","الخامس عشر","السادس عشر","السابع عشر","الثامن عشر","التاسع عشر","العشرون","الحادي والعشرون","الثاني والعشرون","الثالث والعشرون","الرابع والعشرون"];

const state={user:null,account:null,entitlements:[],holidays:[],currentPlan:null,savedPlans:[],editingId:null};
const el=Object.fromEntries([...document.querySelectorAll('[id]')].map(node=>[node.id,node]));
const $all=(selector,root=document)=>[...root.querySelectorAll(selector)];
function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function clean(value){return String(value??"").replace(/\s+/g," ").trim()}
function toast(message,error=false){el.toast.textContent=message;el.toast.classList.toggle('error',error);el.toast.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.toast.hidden=true,3600)}
function showStatus(message,error=false){el.planStatus.hidden=false;el.planStatus.textContent=message;el.planStatus.classList.toggle('error',error)}
function hideStatus(){el.planStatus.hidden=true}
function parseDate(value){if(!value)return null;if(value instanceof Date)return new Date(value);const raw=String(value);const d=/^\d{4}-\d{2}-\d{2}$/.test(raw)?new Date(`${raw}T12:00:00`):new Date(raw);return Number.isNaN(d.getTime())?null:d}
function isoDate(date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
function addDays(date,count){const d=new Date(date);d.setDate(d.getDate()+count);return d}
function startOfSundayWeek(date){const d=new Date(date);d.setDate(d.getDate()-d.getDay());return d}
function formatGregorian(value){const d=value instanceof Date?value:parseDate(value);return d?new Intl.DateTimeFormat('ar-SA',{weekday:'long',day:'numeric',month:'numeric',year:'numeric'}).format(d):'—'}
function formatGregorianShort(value){const d=value instanceof Date?value:parseDate(value);return d?new Intl.DateTimeFormat('ar-SA',{day:'numeric',month:'numeric',year:'numeric'}).format(d):'—'}
function formatHijri(value){const d=value instanceof Date?value:parseDate(value);if(!d)return'—';try{return new Intl.DateTimeFormat('ar-SA-u-ca-islamic-umalqura',{day:'numeric',month:'numeric',year:'numeric'}).format(d)}catch(_){return''}}
function formatBoth(value){return `${formatGregorianShort(value)} م${formatHijri(value)?` — ${formatHijri(value)} هـ`:''}`}
function activeEntitlements(){return(state.entitlements||[]).filter(item=>item.is_active!==false&&item.expires_at&&new Date(item.expires_at).getTime()>Date.now())}
function isAdmin(){return Boolean(state.account?.is_system_admin)}
function hasAccess(code){const active=activeEntitlements();if(isAdmin())return true;if(code==='messages_library')return active.some(item=>item.billing_period==='yearly');return active.some(item=>item.product_code==='all_access'||item.product_code===code)}
function unifiedLaunchKey(code){return`unified_platform_launch_${code}`}
function rememberUnifiedLaunch(code){try{sessionStorage.setItem(unifiedLaunchKey(code),String(Date.now()));sessionStorage.setItem('unified_last_platform',code)}catch(_){}}
function clearUnifiedLaunches(){try{Object.keys(sessionStorage).filter(key=>key.startsWith('unified_platform_launch_')).forEach(key=>sessionStorage.removeItem(key));sessionStorage.removeItem('unified_last_platform')}catch(_){}}
function cameFromUnifiedPortal(){const params=new URLSearchParams(location.search);const fromPortal=params.get('from')==='portal';let remembered=false;try{remembered=Boolean(sessionStorage.getItem(unifiedLaunchKey(CURRENT_PACKAGE_CODE)))}catch(_){}if(fromPortal){rememberUnifiedLaunch(CURRENT_PACKAGE_CODE);params.delete('from');history.replaceState({},'',location.pathname+(params.toString()?`?${params}`:''));return true}return remembered}
function redirectToPortal(notice='choose_platform'){try{sessionStorage.setItem('portal_notice',notice==='package_locked'?'منصة خطة الموجه الطلابي غير مشمولة في باقتك الحالية.':'اختر المنصة من بوابة المنصات.')}catch(_){}location.replace(`../index.html?notice=${notice}`)}
function goToUnifiedPlatform(code){const item=UNIFIED_PLATFORM_ROUTES[code];if(!item||item.coming||!hasAccess(code))return;rememberUnifiedLaunch(code);location.href=`${item.href}?from=portal`}
function planMeta(){const active=activeEntitlements();if(isAdmin())return{label:'مدير النظام',detail:'صلاحية كاملة لجميع المنصات'};const all=active.find(x=>x.product_code==='all_access');if(all)return{label:'الباقة الشاملة',detail:`سارية حتى ${formatGregorianShort(all.expires_at)}`};const mine=active.find(x=>x.product_code===CURRENT_PACKAGE_CODE);return mine?{label:PACKAGE_LABELS[CURRENT_PACKAGE_CODE],detail:`سارية حتى ${formatGregorianShort(mine.expires_at)}`}:{label:'حساب غير مشترك',detail:'لا توجد باقة نشطة'}}
function renderPlatformSwitcher(){const meta=planMeta();el.platformSwitcher.innerHTML=Object.entries(UNIFIED_PLATFORM_ROUTES).map(([code,item])=>{const icon=UNIFIED_PLATFORM_ICONS[code]||'';if(item.coming)return`<span class="platform-tab coming"><span class="platform-tab-icon">${icon}</span><span><strong>${item.label}</strong><small>قريبًا</small></span></span>`;if(!hasAccess(code))return`<span class="platform-tab locked"><span class="platform-tab-icon">${icon}</span><span><strong>${item.label}</strong><small>غير مفعّلة</small></span></span>`;const current=code===CURRENT_PACKAGE_CODE;return`<a href="${item.href}?from=portal" data-platform="${code}" class="platform-tab${current?' current':''}"><span class="platform-tab-icon">${icon}</span><span><strong>${item.label}</strong><small>${current?'المنصة الحالية':'انتقال'}</small></span></a>`}).join('');el.platformPlanBadge.innerHTML=`<span class="plan-dot"></span><span><small>الباقة الحالية</small><strong>${escapeHtml(meta.label)}</strong><em>${escapeHtml(meta.detail)}</em></span>`;el.unifiedPlatformBar.hidden=false;$all('[data-platform]',el.platformSwitcher).forEach(link=>link.onclick=e=>{e.preventDefault();goToUnifiedPlatform(link.dataset.platform)})}

function syncPrincipalFromSchoolContext(context=null,{refreshPlan=true}={}){
  const ctx=context||window.MishkatSchoolContext?.getContext?.()||{};
  const name=clean(ctx.managerName||'');
  if(!name)return false;
  if(el.principalName&&el.principalName.value!==name)el.principalName.value=name;
  if(state.currentPlan?.form&&state.currentPlan.form.principalName!==name){
    state.currentPlan.form.principalName=name;
    // The manager is authoritative school identity data. Keep generated/loaded
    // plan output synchronized without requiring the user to regenerate it.
    if(refreshPlan&&!el.planPreviewSection?.hidden)renderPlan();
  }
  return true;
}
function ensurePrincipalFromSchoolContext(){
  if(syncPrincipalFromSchoolContext())return Promise.resolve(true);
  const resolver=window.MishkatSchoolContext?.resolveManagerDirect;
  if(typeof resolver!=='function')return Promise.resolve(false);
  return Promise.resolve(resolver()).then(()=>syncPrincipalFromSchoolContext()).catch(error=>{
    console.warn('Mishkat plan: school manager lookup is still pending.',error);
    return false;
  });
}
function renderIdentity(){const ctx=window.MishkatSchoolContext?.getContext?.()||{};const school=ctx.schoolName||state.account?.school_name||'اسم المدرسة';const user=ctx.counselorName||state.account?.full_name||state.user?.email||'الموجه الطلابي';el.schoolName.textContent=school;el.userName.textContent=user;el.counselorName.value=user;el.principalName.value=ctx.managerName||el.principalName.value||'';const logo=state.account?.school_logo_data;if(logo){el.schoolLogo.src=logo;el.schoolLogo.hidden=false;el.schoolLogoPlaceholder.hidden=true}else{el.schoolLogo.hidden=true;el.schoolLogoPlaceholder.hidden=false;el.schoolLogoPlaceholder.textContent=school.trim().charAt(0)||'م'}}

function holidayCovers(date,holiday){const value=isoDate(date);return value>=holiday.start&&value<=holiday.end}
function overlappingHolidays(days){return state.holidays.filter(h=>days.some(day=>holidayCovers(day,h)))}
function buildCalendarSegments(start,end){let cursor=startOfSundayWeek(start);const raw=[];let weekNumber=0;while(cursor<=end){const workDays=[0,1,2,3,4].map(i=>addDays(cursor,i)).filter(day=>day>=start&&day<=end);if(workDays.length){const holidays=overlappingHolidays(workDays);const activeDays=workDays.filter(day=>!holidays.some(h=>holidayCovers(day,h)));if(activeDays.length){weekNumber++;raw.push({type:'week',number:weekNumber,start:isoDate(activeDays[0]),end:isoDate(activeDays.at(-1)),calendarStart:isoDate(workDays[0]),calendarEnd:isoDate(workDays.at(-1)),holidays:holidays.map(h=>({...h}))})}else{raw.push({type:'holiday',start:isoDate(workDays[0]),end:isoDate(workDays.at(-1)),holidays:holidays.map(h=>({...h}))})}}cursor=addDays(cursor,7)}const merged=[];raw.forEach(segment=>{const prev=merged.at(-1);if(segment.type==='holiday'&&prev?.type==='holiday'&&Math.round((parseDate(segment.start)-parseDate(prev.end))/86400000)<=7){prev.end=segment.end;const map=new Map([...prev.holidays,...segment.holidays].map(h=>[h.id,h]));prev.holidays=[...map.values()]}else merged.push(segment)});return merged}
function weekOrdinal(number){return WEEK_ORDINALS[number-1]||String(number)}
function stagePrograms(stageKey,weekNumber,totalWeeks){const data=STAGES[stageKey];if(weekNumber===totalWeeks)return["متابعة اختبارات نهاية الفصل الدراسي","تقويم الخطة وتوثيق الإنجازات والتوصيات"];if(weekNumber===totalWeeks-1)return["التهيئة النفسية للاختبارات","متابعة الطلاب أثناء الاختبارات"];return data.programs[(weekNumber-1)%data.programs.length]||["برنامج إرشادي حسب الاحتياج","متابعة تنفيذ الخطة"]}
function makeIntroduction(form){const stage=STAGES[form.stage];return`انطلاقًا من رسالة ${form.schoolName||'المدرسة'} في توفير بيئة تعليمية آمنة وداعمة، أعدّ ${form.counselorName||'الموجه الطلابي'} هذه الخطة لتنظيم الأعمال والخدمات والبرامج الموجهة إلى ${stage.audience} خلال ${form.termName} من العام الدراسي ${form.academicYear||'الحالي'}. وقد بُنيت الخطة على الفصل الدراسي الذي يبدأ في ${formatGregorian(form.startDate)} وينتهي في ${formatGregorian(form.endDate)}، مع مراعاة الإجازات والفواصل الدراسية المدخلة. وتركز الخطة في هذه المرحلة على ${stage.focus} كما تتيح متابعة التنفيذ أسبوعيًا، وتوثيق الأعمال المستجدة، والجلسات الفردية، ودراسات الحالة، والإرشاد الجمعي وفق الاحتياج والإمكانات المتاحة.`}
function currentForm(){const ctx=window.MishkatSchoolContext?.getContext?.()||{};return{title:clean(el.planTitle.value)||'خطة الأعمال الأسبوعية للموجه الطلابي',stage:el.schoolStage.value,termName:ctx.term||el.termName.value,academicYear:ctx.academicYear||clean(el.academicYear.value),counselorName:ctx.counselorName||clean(el.counselorName.value),principalName:ctx.managerName||clean(el.principalName.value),schoolName:ctx.schoolName||state.account?.school_name||'اسم المدرسة',startDate:el.studyStart.value,endDate:el.studyEnd.value}}
function validateForm(form){if(!form.startDate||!form.endDate)return'أدخل تاريخ بداية الفصل الدراسي ونهاية الفصل الدراسي.';if(parseDate(form.endDate)<parseDate(form.startDate))return'نهاية الفصل الدراسي يجب أن تكون بعد بداية الفصل الدراسي.';if(!form.counselorName)return'اكتب اسم الموجه الطلابي.';if(!form.academicYear)return'اكتب العام الدراسي.';return''}
function addHoliday(){const title=clean(el.holidayTitle.value),start=el.holidayStart.value,end=el.holidayEnd.value;if(!title||!start||!end)return toast('اكتب اسم الإجازة وتاريخ بدايتها ونهايتها.',true);if(end<start)return toast('نهاية الإجازة يجب أن تكون بعد بدايتها.',true);const holidayId=(globalThis.crypto&&typeof globalThis.crypto.randomUUID==='function')?globalThis.crypto.randomUUID():`holiday-${Date.now()}-${Math.random().toString(16).slice(2)}`;state.holidays.push({id:holidayId,type:el.holidayType.value,title,start,end});state.holidays.sort((a,b)=>a.start.localeCompare(b.start));renderHolidays();el.holidayTitle.value='';el.holidayStart.value='';el.holidayEnd.value=''}
function renderHolidays(){el.holidayCount.textContent=state.holidays.length;el.holidayList.innerHTML=state.holidays.length?state.holidays.map(h=>`<article class="holiday-item"><div><span>${escapeHtml(HOLIDAY_TYPES[h.type]||h.type)}</span><strong>${escapeHtml(h.title)}</strong><small>${formatBoth(h.start)} — ${formatBoth(h.end)}</small></div><button data-delete-holiday="${h.id}" type="button">حذف</button></article>`).join(''):'<div class="empty-inline">لم تتم إضافة إجازات بعد.</div>';$all('[data-delete-holiday]',el.holidayList).forEach(b=>b.onclick=()=>{state.holidays=state.holidays.filter(h=>h.id!==b.dataset.deleteHoliday);renderHolidays()})}
function makeWeekData(segment,form,totalWeeks){const stage=STAGES[form.stage];const tasks=[...COMMON_TASKS,...stage.extras];return{...segment,tasks:tasks.slice(0,8).map((text,index)=>({text,done:false,notDone:false,note:'',fixed:index<4})),programs:stagePrograms(form.stage,segment.number,totalWeeks).map(text=>({text})),weekNote:segment.holidays.length?`يتضمن هذا الأسبوع: ${segment.holidays.map(h=>h.title).join('، ')}.`:'البرامج الإرشادية تنفذ حسب الخطط المعتمدة والإمكانات والاحتياجات الفعلية.',special:{individual:false,caseStudy:false,group:false,notes:['','','']},emerging:[{text:'',done:false,notDone:false},{text:'',done:false,notDone:false},{text:'',done:false,notDone:false},{text:'',done:false,notDone:false}]}}
function generatePlan(){const form=currentForm();const error=validateForm(form);if(error)return showStatus(error,true);const segments=buildCalendarSegments(parseDate(form.startDate),parseDate(form.endDate));const totalWeeks=segments.filter(x=>x.type==='week').length;if(!totalWeeks)return showStatus('لم ينتج عن التقويم أي أسبوع دراسي فعلي. راجع التواريخ والإجازات.',true);const introduction=makeIntroduction(form);state.currentPlan={id:state.editingId||null,form,holidays:JSON.parse(JSON.stringify(state.holidays)),introduction,segments:segments.map(s=>s.type==='week'?makeWeekData(s,form,totalWeeks):s),createdAt:new Date().toISOString()};renderPlan();hideStatus();el.savePlanButton.disabled=false;el.printPlanButton.disabled=false;el.planPreviewSection.hidden=false;el.generatedWeekCount.textContent=totalWeeks;el.planPreviewSection.scrollIntoView({behavior:'smooth',block:'start'})}
function logoMarkup(){const logo=state.account?.school_logo_data;return logo?`<img src="${logo}" alt="شعار المدرسة">`:`<span>${escapeHtml((state.account?.school_name||'م').trim().charAt(0)||'م')}</span>`}
function planHeaderMarkup(form){return`<div class="print-brand"><div class="print-logo">${logoMarkup()}</div><div><strong>${escapeHtml(form.schoolName)}</strong><span>التوجيه الطلابي — ${escapeHtml(STAGES[form.stage].label)}</span></div></div><div class="ministry-mark"><b>وزارة التعليم</b><span>خطة الموجه الطلابي</span></div>`}
function coverPage(plan){const f=plan.form;return`<article class="print-page cover-page"><div class="cover-orb orb-a"></div><div class="cover-orb orb-b"></div><header>${planHeaderMarkup(f)}</header><div class="cover-content"><span>خطة تنفيذية مبنية على التقويم الدراسي</span><h1>${escapeHtml(f.title)}</h1><h2>${escapeHtml(STAGES[f.stage].label)}</h2><div class="cover-dates"><b>${escapeHtml(f.termName)}</b><strong>${escapeHtml(f.academicYear)}</strong></div></div><div class="cover-footer"><div><span>الموجه الطلابي</span><strong>${escapeHtml(f.counselorName)}</strong></div><div><span>مدير المدرسة</span><strong>${escapeHtml(f.principalName||'—')}</strong></div></div></article>`}
function introPage(plan){const f=plan.form;return`<article class="print-page intro-page"><header>${planHeaderMarkup(f)}</header><div class="intro-content"><span class="page-kicker">تمهيد</span><h2>مقدمة الخطة</h2><div id="planIntroductionEditor" class="editable-intro" contenteditable="true">${escapeHtml(plan.introduction)}</div><div class="calendar-summary"><div><span>بداية الفصل الدراسي</span><strong>${formatBoth(f.startDate)}</strong></div><div><span>نهاية الفصل الدراسي</span><strong>${formatBoth(f.endDate)}</strong></div><div><span>المرحلة</span><strong>${escapeHtml(STAGES[f.stage].label)}</strong></div><div><span>عدد أسابيع الدراسة</span><strong>${plan.segments.filter(x=>x.type==='week').length} أسبوعًا</strong></div></div><div class="signature-line"><span>الموجه الطلابي</span><strong>${escapeHtml(f.counselorName)}</strong></div></div></article>`}
function editable(value,cls=''){return`<div class="editable-cell ${cls}" contenteditable="true">${escapeHtml(value||'')}</div>`}
function weekPage(segment,plan,index){const f=plan.form;return`<article class="print-page weekly-page" data-segment-index="${index}" data-week-number="${segment.number}"><header class="weekly-header">${planHeaderMarkup(f)}</header><div class="week-title"><span>الأسبوع ${weekOrdinal(segment.number)}</span><div><strong>${formatGregorian(segment.start)}</strong><i>إلى</i><strong>${formatGregorian(segment.end)}</strong></div><small>${formatHijri(segment.start)} هـ — ${formatHijri(segment.end)} هـ</small></div><div class="weekly-layout"><section class="tasks-section"><table><thead><tr><th>م</th><th>الأعمال والخدمات</th><th>نفذ</th><th>لم ينفذ</th><th>ملاحظات</th></tr></thead><tbody>${segment.tasks.map((task,i)=>`<tr data-task-index="${i}"><td>${i+1}</td><td>${editable(task.text,'task-text')}${task.fixed?'<small class="fixed-mark">عمل ثابت</small>':''}</td><td><input class="task-done" type="checkbox" ${task.done?'checked':''}></td><td><input class="task-not-done" type="checkbox" ${task.notDone?'checked':''}></td><td>${editable(task.note,'task-note')}</td></tr>`).join('')}</tbody></table></section><aside class="side-sections"><section class="programs-box"><h3>البرامج الإرشادية في هذا الأسبوع</h3>${segment.programs.map((p,i)=>`<div data-program-index="${i}">${editable(p.text,'program-text')}</div>`).join('')}<h4>ملاحظات</h4>${editable(segment.weekNote,'week-note')}</section><section class="special-box"><h3>أعمال التوجيه الخاصة</h3><div class="special-checks"><label><input class="special-individual" type="checkbox" ${segment.special.individual?'checked':''}> جلسة فردية</label><label><input class="special-case" type="checkbox" ${segment.special.caseStudy?'checked':''}> دراسة حالة</label><label><input class="special-group" type="checkbox" ${segment.special.group?'checked':''}> إرشاد جمعي</label></div>${segment.special.notes.map((n,i)=>`<div data-special-note-index="${i}">${editable(n,'special-note')}</div>`).join('')}</section></aside><section class="emerging-section"><table><thead><tr><th>م</th><th>ما يستجد من أعمال وخدمات</th><th>نفذ</th><th>لم ينفذ</th></tr></thead><tbody>${segment.emerging.map((item,i)=>`<tr data-emerging-index="${i}"><td>${i+1}</td><td>${editable(item.text,'emerging-text')}</td><td><input class="emerging-done" type="checkbox" ${item.done?'checked':''}></td><td><input class="emerging-not-done" type="checkbox" ${item.notDone?'checked':''}></td></tr>`).join('')}</tbody></table></section></div><footer class="weekly-footer"><p>◆ أعمال ثابتة يقوم بها الموجه الطلابي يوميًا. ◆ تستخدم الوسائل التقنية والإعلامية المتاحة بعد أخذ الموافقات اللازمة. ◆ برامج مستمرة طوال العام الدراسي.</p><span>${escapeHtml(f.counselorName)} — ${escapeHtml(f.schoolName)}</span></footer></article>`}
function holidayPage(segment,plan,index){const f=plan.form;const titles=segment.holidays.map(h=>h.title).join(' — ')||'إجازة دراسية';return`<article class="print-page holiday-page" data-segment-index="${index}"><header>${planHeaderMarkup(f)}</header><div class="holiday-page-content"><div class="holiday-symbol">☼</div><span>فاصل في التقويم الدراسي</span><h2>${escapeHtml(titles)}</h2><p>${formatBoth(segment.start)} — ${formatBoth(segment.end)}</p><small>لا تحتسب هذه المدة ضمن ترقيم أسابيع الدراسة الفعلية.</small></div></article>`}
function renderPlan(){const plan=state.currentPlan;if(!plan)return;el.planDocument.innerHTML=coverPage(plan)+introPage(plan)+plan.segments.map((s,i)=>s.type==='week'?weekPage(s,plan,i):holidayPage(s,plan,i)).join('');const intro=el.planDocument.querySelector('#planIntroductionEditor');if(intro)intro.oninput=()=>{state.currentPlan.introduction=clean(intro.textContent)}}
function collectEdits(){if(!state.currentPlan)return;const intro=el.planDocument.querySelector('#planIntroductionEditor');if(intro)state.currentPlan.introduction=clean(intro.textContent);$all('.weekly-page',el.planDocument).forEach(page=>{const idx=Number(page.dataset.segmentIndex);const segment=state.currentPlan.segments[idx];$all('tbody tr[data-task-index]',page).forEach(row=>{const task=segment.tasks[Number(row.dataset.taskIndex)];task.text=clean(row.querySelector('.task-text')?.textContent);task.note=clean(row.querySelector('.task-note')?.textContent);task.done=row.querySelector('.task-done').checked;task.notDone=row.querySelector('.task-not-done').checked});$all('[data-program-index]',page).forEach(row=>segment.programs[Number(row.dataset.programIndex)].text=clean(row.querySelector('.program-text')?.textContent));segment.weekNote=clean(page.querySelector('.week-note')?.textContent);segment.special.individual=page.querySelector('.special-individual').checked;segment.special.caseStudy=page.querySelector('.special-case').checked;segment.special.group=page.querySelector('.special-group').checked;$all('[data-special-note-index]',page).forEach(row=>segment.special.notes[Number(row.dataset.specialNoteIndex)]=clean(row.querySelector('.special-note')?.textContent));$all('tbody tr[data-emerging-index]',page).forEach(row=>{const item=segment.emerging[Number(row.dataset.emergingIndex)];item.text=clean(row.querySelector('.emerging-text')?.textContent);item.done=row.querySelector('.emerging-done').checked;item.notDone=row.querySelector('.emerging-not-done').checked})})}
async function savePlan(){if(!state.currentPlan)return;collectEdits();el.savePlanButton.disabled=true;try{const p=state.currentPlan;const payload={user_id:state.user.id,title:p.form.title,school_name:p.form.schoolName,counselor_name:p.form.counselorName,principal_name:p.form.principalName||null,school_stage:p.form.stage,academic_year:p.form.academicYear||null,term_name:p.form.termName,start_date:p.form.startDate,end_date:p.form.endDate,introduction:p.introduction,holidays:p.holidays,plan_data:{segments:p.segments,form:p.form},status:'draft'};let result;if(state.editingId){result=await db.from('counselor_plans').update(payload).eq('id',state.editingId).select().single()}else{result=await db.from('counselor_plans').insert(payload).select().single()}if(result.error)throw result.error;state.editingId=result.data.id;state.currentPlan.id=result.data.id;toast('تم حفظ الخطة بنجاح.');await loadSavedPlans()}catch(error){toast(error.message||'تعذر حفظ الخطة.',true)}finally{el.savePlanButton.disabled=false}}
async function loadSavedPlans(){const{data,error}=await db.from('counselor_plans').select('id,title,school_stage,academic_year,term_name,start_date,end_date,updated_at').eq('user_id',state.user.id).order('updated_at',{ascending:false});if(error){el.savedPlansList.innerHTML='<div class="status-box error">تعذر تحميل الخطط المحفوظة.</div>';return}state.savedPlans=data||[];renderSavedPlans()}
function renderSavedPlans(){el.savedPlansList.innerHTML=state.savedPlans.length?state.savedPlans.map(p=>`<article class="saved-plan-item"><div><span>${escapeHtml(STAGES[p.school_stage]?.label||p.school_stage)}</span><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.term_name||'')} — ${escapeHtml(p.academic_year||'')} — ${formatGregorianShort(p.start_date)} إلى ${formatGregorianShort(p.end_date)}</p><small>آخر تعديل: ${formatGregorianShort(p.updated_at)}</small></div><div><button class="secondary-button" data-open-plan="${p.id}" type="button">فتح</button><button class="danger-button" data-delete-plan="${p.id}" type="button">حذف</button></div></article>`).join(''):'<div class="empty-inline">لا توجد خطط محفوظة بعد.</div>';$all('[data-open-plan]',el.savedPlansList).forEach(b=>b.onclick=()=>openSavedPlan(b.dataset.openPlan));$all('[data-delete-plan]',el.savedPlansList).forEach(b=>b.onclick=()=>deleteSavedPlan(b.dataset.deletePlan))}
async function openSavedPlan(id){const{data,error}=await db.from('counselor_plans').select('*').eq('id',id).single();if(error)return toast('تعذر فتح الخطة.',true);state.editingId=data.id;state.holidays=Array.isArray(data.holidays)?data.holidays:[];const form=data.plan_data?.form||{title:data.title,stage:data.school_stage,academicYear:data.academic_year,termName:data.term_name,counselorName:data.counselor_name,principalName:data.principal_name,schoolName:data.school_name,startDate:data.start_date,endDate:data.end_date};state.currentPlan={id:data.id,form,holidays:state.holidays,introduction:data.introduction||'',segments:data.plan_data?.segments||[]};el.planTitle.value=form.title;el.schoolStage.value=form.stage;el.academicYear.value=form.academicYear||'';el.termName.value=form.termName||'الفصل الدراسي الأول';el.counselorName.value=form.counselorName||'';el.principalName.value=form.principalName||'';el.studyStart.value=form.startDate;el.studyEnd.value=form.endDate;renderHolidays();renderPlan();el.generatedWeekCount.textContent=state.currentPlan.segments.filter(x=>x.type==='week').length;el.planPreviewSection.hidden=false;el.savePlanButton.disabled=false;el.printPlanButton.disabled=false;syncPrincipalFromSchoolContext();el.planPreviewSection.scrollIntoView({behavior:'smooth'})}
async function deleteSavedPlan(id){if(!confirm('حذف هذه الخطة نهائيًا؟'))return;const{error}=await db.from('counselor_plans').delete().eq('id',id);if(error)return toast('تعذر حذف الخطة.',true);if(state.editingId===id)newPlan();toast('تم حذف الخطة.');await loadSavedPlans()}
function newPlan(){state.editingId=null;state.currentPlan=null;state.holidays=[];el.planPreviewSection.hidden=true;el.planDocument.innerHTML='';el.savePlanButton.disabled=true;el.printPlanButton.disabled=true;{const ctx=window.MishkatSchoolContext?.getContext?.()||{};el.planTitle.value=ctx.schoolType==='girls'?'خطة الأعمال الأسبوعية للموجهة الطلابية':'خطة الأعمال الأسبوعية للموجه الطلابي';window.MishkatSchoolContext?.applyDocument?.(document);if(ctx.term)el.termName.value=ctx.term;if(ctx.academicYear)el.academicYear.value=ctx.academicYear;if(ctx.managerName)el.principalName.value=ctx.managerName;}el.studyStart.value='';el.studyEnd.value='';renderHolidays();hideStatus();window.scrollTo({top:0,behavior:'smooth'})}
function printPlan(){if(!state.currentPlan)return;collectEdits();document.body.classList.add('printing-plan');window.print()}
async function loadAccount(){let{data,error}=await db.from('premium_accounts').select('user_id,full_name,email,school_name,school_logo_data,is_system_admin,is_active').eq('user_id',state.user.id).single();if(error)throw error;state.account=data;const result=await db.from('premium_entitlements').select('id,user_id,product_code,billing_period,expires_at,is_active').eq('user_id',state.user.id).order('expires_at',{ascending:false});if(result.error)throw result.error;state.entitlements=result.data||[]}
async function init(){const{data:{session}}=await db.auth.getSession();if(!session)return redirectToPortal('choose_platform');state.user=session.user;try{await loadAccount();if(state.account?.is_active===false)throw new Error('هذا الحساب موقوف.');if(!hasAccess(CURRENT_PACKAGE_CODE))return redirectToPortal('package_locked');if(!cameFromUnifiedPortal())return redirectToPortal('choose_platform');renderPlatformSwitcher();renderIdentity();el.accessGate.hidden=true;el.appShell.hidden=false;await loadSavedPlans()}catch(error){el.accessGate.innerHTML=`<div class="gate-error"><strong>تعذر فتح المنصة</strong><p>${escapeHtml(error.message||'حدث خطأ غير متوقع.')}</p><a href="../index.html">العودة إلى البوابة</a></div>`}}
function bind(){el.addHolidayButton.onclick=addHoliday;el.generatePlanButton.onclick=generatePlan;el.savePlanButton.onclick=savePlan;el.printPlanButton.onclick=printPlan;el.newPlanButton.onclick=newPlan;el.refreshPlansButton.onclick=loadSavedPlans;window.addEventListener('mishkat:school-context-ready',event=>{syncPrincipalFromSchoolContext(event.detail)});window.addEventListener('mishkat:school-context-changed',event=>{syncPrincipalFromSchoolContext(event.detail)});window.addEventListener('mishkat:directory-loaded',()=>{ensurePrincipalFromSchoolContext()});window.addEventListener('afterprint',()=>document.body.classList.remove('printing-plan'));document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();if(state.currentPlan)savePlan()}})}
bind();init();
